/* Dados iniciais — inseridos na primeira vez que entras na conta */
window.MARE_SEED = {
  recipes: [
    // Manhã
    { section: "manha", title: "Ovos mexidos com queijo e fiambre", subtitle: "Clássico cremoso · 8 min", protein_note: "~25 g proteína", tags: ["1 panela"], ingredients: ["3 ovos", "2 fatias fiambre ou peito de peru", "Queijo ralado generoso", "Manteiga, sal, pimenta · pão opcional"], steps: ["Bate os ovos com sal.", "Derrete manteiga em lume baixo-médio, deita os ovos e mexe devagar.", "Junta fiambre picado e queijo. Tira do lume um pouco antes de secar."] },
    { section: "manha", title: "Iogurte grego com mel e granola", subtitle: "Sem fogão · 2 min", protein_note: "~20 g proteína", tags: ["sem fogão"], ingredients: ["200–250 g iogurte grego", "Mel + granola", "Opcional: banana, pasta de amendoim"], steps: ["Deita o iogurte, rega com mel, granola por cima.", "Para mais proteína: 1 colher de pasta de amendoim misturada."] },
    { section: "manha", title: "Tosta de ovo e queijo derretido", subtitle: "Tipo brunch · 10 min", protein_note: "~22 g proteína", tags: ["confortável"], ingredients: ["2 fatias de pão bom", "2 ovos + 2 fatias de queijo", "Manteiga · opcional fiambre"], steps: ["Tosta o pão com manteiga e derrete o queijo em cima.", "Frita os ovos (gema mole fica top) e empilha."] },
    { section: "manha", title: "Wrap de peito de peru e ovo", subtitle: "Para levar · 10 min", protein_note: "~28 g proteína", tags: ["leva-te"], ingredients: ["1 tortilha grande", "2–3 fatias peito de peru", "1 ovo mexido ou frito", "Queijo ou cream cheese"], steps: ["Coze o ovo, aquece a tortilha.", "Espalha queijo, põe peru e ovo, enrolha apertado."] },
    { section: "manha", title: "Scramble de ovos com atum", subtitle: "Proteína a dobrar · 8 min", protein_note: "~32 g proteína", tags: ["lata"], ingredients: ["3 ovos", "½ lata de atum escorrido", "Queijo ralado, azeite ou manteiga", "Sal, pimenta, orégãos"], steps: ["Refoga o atum 30 seg na manteiga.", "Deita os ovos batidos, mexe, junta queijo no fim."] },
    { section: "manha", title: "Pão com cream cheese e salmão fumado", subtitle: "Sem fogão · 5 min", protein_note: "~22 g proteína", tags: ["frio"], ingredients: ["2 fatias pão mole ou baguete", "Cream cheese", "80–100 g salmão fumado", "Limão, pimenta"], steps: ["Espalha cream cheese, cobre com salmão.", "Gotas de limão e pimenta. Pronto."] },
    { section: "manha", title: "Panquecas salgadas de fiambre e queijo", subtitle: "Massa simples · 15 min", protein_note: "~24 g proteína", tags: ["frigideira"], ingredients: ["2 ovos + 4 colheres de sopa farinha + 4 de leite", "Fiambre picado + queijo ralado", "Sal, pimenta, manteiga"], steps: ["Bate ovos, farinha, leite e temperos. Junta fiambre e queijo.", "Frita colheradas na manteiga até dourar dos dois lados."] },
    { section: "manha", title: "Skyr / quark com pasta de amendoim", subtitle: "Colher · proteína alta", protein_note: "~25 g+ proteína", tags: ["sem fogão"], ingredients: ["200 g skyr, quark ou cottage", "1–2 colheres pasta de amendoim cremosa", "Mel ou banana amassada"], steps: ["Mistura tudo na taça até ficar cremoso. Come com colher."] },

    // Praia
    { section: "praia", title: "Sandes de patê de atum", subtitle: "A tua receita · base da praia", protein_note: "atum = proteína", tags: ["mala térmica"], ingredients: ["Usa a receita que já tens", "Ovo cozido picado no patê (opcional)", "Wrap em vez de pão (opcional)", "Alface à parte"], steps: ["Prepara o patê como costumas.", "Varia com ovo picado ou wrap.", "Mantém frio na mala térmica."], note: "Mantém frio na mala térmica — atum e maionese não gostam de calor." },
    { section: "praia", title: "Wrap de frango desfiado", subtitle: "Salada de frango cremosa", protein_note: "~30 g proteína", tags: ["preparar à noite"], ingredients: ["250–300 g frango cozido/assado desfiado", "2–3 c. sopa maionese (ou metade iogurte grego)", "Limão, sal, pimenta, orégãos", "2 tortilhas + alface"], steps: ["Mistura frango com maionese e temperos até ficar cremoso.", "Espalha nos wraps, alface, enrolha. Embala frio."] },
    { section: "praia", title: "Sandes de ovo e maionese", subtitle: "Clássica mole · fria", protein_note: "~20 g proteína", tags: ["fria"], ingredients: ["4–5 ovos cozidos", "2–3 c. sopa maionese", "Sal, pimenta · mostarda opcional", "Pão de forma mole"], steps: ["Coze 9–10 min, descasca, esmaga com garfo.", "Mistura maionese, tempera, espalha no pão."] },
    { section: "praia", title: "Bagels de salmão e cream cheese", subtitle: "Sem fogão · 5 min", protein_note: "~25 g proteína", tags: ["sem fogão"], ingredients: ["100–120 g salmão fumado", "Cream cheese", "2 wraps ou baguete macia", "Limão, pimenta"], steps: ["Cream cheese → salmão → limão. Enrolha. Mantém bem frio."] },
    { section: "praia", title: "Sandes de atum e ovo (dupla)", subtitle: "Patê reforçado", protein_note: "~32 g proteína", tags: ["fria"], ingredients: ["1 lata grande atum escorrido", "2 ovos cozidos picados", "Maionese, sal, pimenta, orégãos", "Pão mole"], steps: ["Mistura tudo até patê cremoso. Espalha e embala."] },
    { section: "praia", title: "Wrap de fiambre, queijo e ovo cozido", subtitle: "Zero confusão · monta e vai", protein_note: "~26 g proteína", tags: ["rápido"], ingredients: ["1–2 wraps", "Fiambre ou peru em fatias", "Queijo em fatias + 1 ovo cozido esmagado com maionese", "Alface opcional"], steps: ["Espalha o ovo com maionese, põe fiambre e queijo, enrolha bem."] },
    { section: "praia", title: "Sandes de frango assado e maionese", subtitle: "Usa frango do supermercado", protein_note: "~28 g proteína", tags: ["compra pronta"], ingredients: ["Frango assado desfiado (compra pronto)", "Maionese ou alho", "Pão mole, alface, tomate"], steps: ["Mistura frango com um pouco de maionese.", "Monta a sandes. Leva frio."] },
    { section: "praia", title: "Bagels de ricotta / requeijão e peru", subtitle: "Muito mole · leve no estômago", protein_note: "~22 g proteína", tags: ["soft"], ingredients: ["Requeijão ou ricotta", "Peito de peru em fatias", "Wrap ou pão de leite", "Opcional: orégãos, azeite"], steps: ["Espalha o queijo cremoso, cobre com peru, enrolha."] },
    { section: "praia", title: "Patê de sardinha com ovo", subtitle: "Alternativa ao atum · lata", protein_note: "~28 g proteína", tags: ["lata"], ingredients: ["1–2 latas sardinha em azeite", "1–2 ovos cozidos", "Maionese ou azeite da lata + limão", "Pão mole"], steps: ["Esmaga sardinha + ovo com garfo, mistura maionese/limão.", "Espalha no pão."] },
    { section: "praia", title: "Mini baguetes de queijo e fiambre", subtitle: "Tipo snack-almoço · várias", protein_note: "~20 g proteína", tags: ["partilhável"], ingredients: ["Baguete macia cortada em 3–4", "Fiambre + queijo em fatias", "Manteiga ou maionese"], steps: ["Abre, unta, mete fiambre e queijo.", "Para mais proteína: ovo cozido picado por dentro."] },

    // Lanches
    { section: "lanches", title: "Iogurte grego com mel", subtitle: "Cremoso · colher", protein_note: "~15–20 g", tags: ["soft"], ingredients: ["Frasco de iogurte grego + mel", "Banana amassada ou pasta de amendoim (opcional)"], steps: ["Abre, rega com mel, come."] },
    { section: "lanches", title: "Queijo fresco com pão mole", subtitle: "Espalha e come", protein_note: "~12–18 g", tags: ["soft"], ingredients: ["Queijo fresco ou requeijão", "Pão de leite / brioche", "Fiambre fininho (opcional)"], steps: ["Espalha no pão. Fiambre por cima se quiseres."] },
    { section: "lanches", title: "Ovos cozidos com sal", subtitle: "Batch · cabem no saco", protein_note: "~6 g / ovo", tags: ["soft"], ingredients: ["Ovos", "Sal"], steps: ["Coze 9–10 min, arrefece, descasca.", "Gema um pouco mole = mais agradável no calor."] },
    { section: "lanches", title: "Smoothie banana, leite e amendoim", subtitle: "Bebível · sem mastigar", protein_note: "~18–25 g", tags: ["líquido"], ingredients: ["1 banana madura", "300 ml leite (+ iogurte grego se quiseres)", "1–2 c. sopa pasta de amendoim cremosa"], steps: ["Tritura até liso. Garrafa térmica fria se levares à praia."] },
    { section: "lanches", title: "Hummus com pita mole", subtitle: "Pasta + pão quentinho", protein_note: "~10–15 g", tags: ["soft"], ingredients: ["Hummus", "Pita", "Queijo fresco ou ovo cozido (extra proteína)"], steps: ["Aquece a pita 30 seg na frigideira.", "Come com hummus."] },
    { section: "lanches", title: "Cottage / quark com fruta mole", subtitle: "Colher · proteína alta", protein_note: "~20 g+", tags: ["soft"], ingredients: ["Cottage, quark ou skyr", "Banana, manga ou pêssego maduro", "Mel"], steps: ["Junta fruta e mel. Come com colher."] },
    { section: "lanches", title: "Pão de leite com pasta de amendoim", subtitle: "Macio · doce-salgado", protein_note: "~12 g", tags: ["soft"], ingredients: ["Pão de leite ou brioche", "Pasta de amendoim cremosa", "Banana (opcional)"], steps: ["Espalha pasta generosa. Banana em cima se tiveres."] },
    { section: "lanches", title: "Creme de atum à colher", subtitle: "Patê sem sandes", protein_note: "~20 g", tags: ["soft"], ingredients: ["Atum + maionese", "Pão muito mole ou wrap cortado"], steps: ["Mistura o patê num recipiente.", "Come à colher ou com pão mole."], note: "Evita crackers duros se quiseres manter o lanche soft." },
    { section: "lanches", title: "Queijo fundido no pão", subtitle: "Quente e mole · 3 min", protein_note: "~15 g", tags: ["quente"], ingredients: ["Pão + fatia grossa de queijo", "Fiambre (opcional)"], steps: ["Derrete na frigideira tapada ou microondas 30–40 seg."] },

    // Jantar
    { section: "jantar", title: "Hambúrgueres caseiros", subtitle: "Carne · queijo · pão", protein_note: "~35–45 g", tags: ["estrela"], ingredients: ["400 g carne picada", "2 pães + cheddar", "Alface, tomate, cebola, molhos"], steps: ["Tempera, forma 2 discos.", "Frita/grelha 3–4 min/lado, derrete queijo no fim.", "Tosta pães, monta."] },
    { section: "jantar", title: "Frango na frigideira + batata", subtitle: "Panado rápido", protein_note: "~40 g", tags: ["frigideira"], ingredients: ["2 peitos em filetes finos", "Ovo + pão ralado temperado", "Batatas a acompanhar"], steps: ["Tempera, passa no ovo e pão ralado.", "Frita até dourar. Serve com batata e maionese/limão."] },
    { section: "jantar", title: "Massa com carne picada", subtitle: "Bolonhesa rápida", protein_note: "~30–40 g", tags: ["1 panela"], ingredients: ["300–400 g massa", "400 g carne picada", "Cebola, alho, tomate pelado", "Queijo ralado"], steps: ["Refoga cebola/alho, coze a carne, junta tomate 10–15 min.", "Mistura com a massa. Queijo sem medo."] },
    { section: "jantar", title: "Quesadillas de frango e queijo", subtitle: "15 min · frigideira", protein_note: "~35 g", tags: ["rápido"], ingredients: ["2 tortilhas", "Frango desfiado ou fiambre", "Queijo ralado generoso"], steps: ["Recheia, doura dos dois lados até derreter. Corta em 4.", "Molho: iogurte grego ou maionese."] },
    { section: "jantar", title: "Omelete carregada", subtitle: "Jantar de ovo · 10 min", protein_note: "~35 g", tags: ["preguiçoso"], ingredients: ["4 ovos", "Fiambre + queijo ralado", "Pão ou batata"], steps: ["Bate ovos, fricciona na manteiga, junta fiambre e queijo, dobra."] },
    { section: "jantar", title: "Bifanas no pão", subtitle: "À portuguesa", protein_note: "~35–40 g", tags: ["tacho"], ingredients: ["300–400 g bifanas", "Alho, louro, vinho branco ou cerveja", "Pão de trigo bom"], steps: ["Doura as bifanas com alho, tempera, rega com vinho e reduz.", "Mete no pão com o molho."] },
    { section: "jantar", title: "Bife com ovo a cavalo", subtitle: "Clássico de tasca", protein_note: "~40 g+", tags: ["frigideira"], ingredients: ["1 bife por pessoa", "1–2 ovos", "Batata frita ou pão", "Manteiga / azeite, sal, pimenta, alho"], steps: ["Frita o bife como gostas. No fim, ovo estrelado em cima.", "Serve com batata ou pão para molhar."] },
    { section: "jantar", title: "Tacos / wraps de carne picada", subtitle: "Estilo mexicano simples", protein_note: "~35 g", tags: ["fun"], ingredients: ["400 g carne picada", "Cebola, alho, cominhos ou paprika, sal", "Tortilhas, queijo, alface, tomate", "Iogurte grego ou maionese"], steps: ["Refoga carne com cebola e temperos até bem cozida.", "Aquece tortilhas, recheia, queijo por cima."] },
    { section: "jantar", title: "Esparguete com atum e alho", subtitle: "Despensa · 15 min", protein_note: "~30 g", tags: ["lata"], ingredients: ["250 g esparguete", "2 latas atum", "Alho, azeite, malagueta opcional", "Orégãos · queijo se quiseres"], steps: ["Coze a massa. Numa frigideira, alho no azeite, junta atum.", "Mistura a massa com uma concha de água da cozedura."] },
    { section: "jantar", title: "Pizza na frigideira (wrap ou pão)", subtitle: "Queijo + fiambre derretidos", protein_note: "~28 g", tags: ["frigideira"], ingredients: ["Wrap grande ou pão pita", "Molho de tomate / passata", "Queijo ralado + fiambre / pepperoni / frango"], steps: ["Na frigideira: base → tomate → queijo e toppings.", "Tapa 3–5 min em lume baixo até derreter. Corta como pizza."] },
  ],

  shopping: [
    { category: "proteina", label: "Ovos (muitos)" },
    { category: "proteina", label: "Atum em lata" },
    { category: "proteina", label: "Sardinhas em lata" },
    { category: "proteina", label: "Peito de frango / frango assado" },
    { category: "proteina", label: "Carne picada" },
    { category: "proteina", label: "Bifanas ou bife" },
    { category: "proteina", label: "Fiambre / peito de peru" },
    { category: "proteina", label: "Salmão fumado" },
    { category: "proteina", label: "Iogurte grego" },
    { category: "proteina", label: "Skyr / quark / cottage" },
    { category: "proteina", label: "Queijo (fatias + ralado)" },
    { category: "proteina", label: "Queijo fresco / requeijão" },
    { category: "proteina", label: "Cream cheese" },
    { category: "proteina", label: "Pasta de amendoim cremosa" },
    { category: "bases", label: "Pão mole / de forma / de leite" },
    { category: "bases", label: "Wraps / tortilhas" },
    { category: "bases", label: "Pão de hambúrguer" },
    { category: "bases", label: "Massa" },
    { category: "bases", label: "Pita" },
    { category: "bases", label: "Maionese" },
    { category: "bases", label: "Tomate pelado / passata" },
    { category: "bases", label: "Hummus" },
    { category: "bases", label: "Leite" },
    { category: "bases", label: "Mel, granola" },
    { category: "bases", label: "Pão ralado" },
    { category: "frescos", label: "Alface, tomate, pepino" },
    { category: "frescos", label: "Cebola, alho" },
    { category: "frescos", label: "Bananas maduras" },
    { category: "frescos", label: "Limões" },
    { category: "frescos", label: "Batatas" },
    { category: "frescos", label: "Azeite, manteiga" },
    { category: "frescos", label: "Sal, pimenta, orégãos" },
    { category: "frescos", label: "Mala térmica + gelo" },
  ],
};
