/* Gerado por scripts/gen_seed.py — passos em PT; note com URL de referência bem avaliada */
window.MARE_SEED = {
  recipes: [
    {
      section: "manha",
      title: "Ovos mexidos cremosos",
      subtitle: "Lume baixo · 8–10 min",
      protein_note: "~20–25 g",
      tags: ["clássico"],
      ingredients: ["3 ovos", "manteiga", "sal e pimenta", "pão"],
      steps: ["Bate ovos só até misturar.", "Derrete manteiga em lume baixo.", "Mexe devagar das bordas ao centro.", "Tira do lume ainda húmidos.", "Serve com pão."],
      note: "Baseado em técnicas clássicas · ref. Serious Eats scrambled eggs: https://www.seriouseats.com/fluffy-scrambled-eggs",
    },
    {
      section: "manha",
      title: "French toast clássico",
      subtitle: "15 min",
      protein_note: "~12 g",
      tags: ["doce"],
      ingredients: ["4 fatias pão grosso", "2 ovos", "120 ml leite", "baunilha", "canela", "manteiga", "mel"],
      steps: ["Bate ovos, leite, baunilha e canela.", "Molha o pão 10–15 s por lado.", "Frita em manteiga até dourar.", "Serve com mel."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes French Toast: https://www.allrecipes.com/recipe/7016/french-toast-i/",
    },
    {
      section: "manha",
      title: "Panquecas fofas",
      subtitle: "20 min",
      protein_note: "~10 g",
      tags: ["doce"],
      ingredients: ["150 g farinha", "fermento", "açúcar", "1 ovo", "200 ml leite", "manteiga derretida", "sal"],
      steps: ["Mistura secos.", "Junta ovo, leite e manteiga sem bater demais.", "Frita conchas; vira quando houver bolhas.", "Empilha e serve."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes pancakes: https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/",
    },
    {
      section: "manha",
      title: "Egg muffins de forno",
      subtitle: "Meal prep · 22 min",
      protein_note: "~12 g/2",
      tags: ["forno"],
      ingredients: ["8 ovos", "espinafres", "tomate", "queijo", "fiambre", "sal"],
      steps: ["Forno 180 °C; unta forma.", "Divide recheios pelos alvéolos.", "Deita ovos batidos.", "Coze 18–22 min."],
      note: "Baseado em técnicas clássicas · ref. NYT Egg Muffins: https://cooking.nytimes.com/recipes/1026058-egg-muffins",
    },
    {
      section: "manha",
      title: "Overnight oats",
      subtitle: "Noite anterior",
      protein_note: "~14 g",
      tags: ["sem fogão"],
      ingredients: ["80 g aveia", "150 ml leite", "chia", "mel", "fruta"],
      steps: ["Mistura tudo num frasco.", "Frio durante a noite.", "De manhã envolve e junta fruta."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes overnight oats: https://www.allrecipes.com/recipe/240406/overnight-oats/",
    },
    {
      section: "manha",
      title: "Iogurte grego com granola",
      subtitle: "2 min",
      protein_note: "~20 g",
      tags: ["sem fogão"],
      ingredients: ["iogurte grego", "granola", "mel", "fruta"],
      steps: ["Deita iogurte.", "Mel em fio.", "Granola por cima."],
      note: "Baseado em técnicas clássicas · ref. BBC breakfast: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes",
    },
    {
      section: "manha",
      title: "Tosta de abacate e ovo",
      subtitle: "12 min",
      protein_note: "~18 g",
      tags: ["brunch"],
      ingredients: ["pão", "1 abacate", "2 ovos", "limão", "sal"],
      steps: ["Tosta o pão.", "Esmaga abacate com limão e sal.", "Frita/pocha ovos.", "Monta."],
      note: "Baseado em técnicas clássicas · ref. BBC avocado toast: https://www.bbcgoodfood.com/recipes/smashed-avocado-on-toast",
    },
    {
      section: "manha",
      title: "Burrito de pequeno-almoço",
      subtitle: "20 min",
      protein_note: "~25 g",
      tags: ["completo"],
      ingredients: ["2 ovos", "batata", "queijo", "tortilha", "salsa"],
      steps: ["Doura batata.", "Junta ovos mexidos e queijo.", "Recheia tortilha e enrola."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes breakfast burritos: https://www.allrecipes.com/recipe/16354/breakfast-burritos/",
    },
    {
      section: "manha",
      title: "Shakshuka",
      subtitle: "25 min",
      protein_note: "~20 g",
      tags: ["1 panela"],
      ingredients: ["cebola", "pimento", "alho", "tomate pelado", "4 ovos", "cominhos", "paprika", "pão"],
      steps: ["Refoga cebola e pimento.", "Junta tomate e especiarias 10 min.", "Parte ovos em covas; tapa 5–8 min.", "Serve com pão."],
      note: "Baseado em técnicas clássicas · ref. NYT shakshuka: https://cooking.nytimes.com/recipes/1014721-shakshuka-with-feta",
    },
    {
      section: "manha",
      title: "Omelete francesa de queijo",
      subtitle: "10 min",
      protein_note: "~22 g",
      tags: ["rápido"],
      ingredients: ["3 ovos", "queijo", "manteiga", "sal", "ervas"],
      steps: ["Bate ovos.", "Coze em manteiga puxando bordas.", "Queijo no centro; dobra."],
      note: "Baseado em técnicas clássicas · ref. Serious Eats omelette: https://www.seriouseats.com/the-best-french-omelette-recipe",
    },
    {
      section: "manha",
      title: "Porridge de aveia",
      subtitle: "12 min",
      protein_note: "~10 g",
      tags: ["quente"],
      ingredients: ["80 g aveia", "300 ml leite", "sal", "mel", "fruta"],
      steps: ["Coze aveia no leite mexendo.", "Ajusta espessura.", "Serve com mel e fruta."],
      note: "Baseado em técnicas clássicas · ref. BBC porridge: https://www.bbcgoodfood.com/recipes/perfect-porridge",
    },
    {
      section: "manha",
      title: "Smoothie bowl de banana",
      subtitle: "5 min",
      protein_note: "~18 g",
      tags: ["líquido"],
      ingredients: ["2 bananas congeladas", "leite", "pasta amendoim", "granola"],
      steps: ["Tritura até creme espesso.", "Deita na taça.", "Toppings."],
      note: "Baseado em técnicas clássicas · ref. BBC smoothies: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "manha",
      title: "Tosta salmão e cream cheese",
      subtitle: "5 min",
      protein_note: "~22 g",
      tags: ["frio"],
      ingredients: ["pão", "cream cheese", "salmão fumado", "limão"],
      steps: ["Espalha cream cheese.", "Cobre com salmão.", "Limão e pimenta."],
      note: "Baseado em técnicas clássicas · ref. BBC smoked salmon bagel: https://www.bbcgoodfood.com/recipes/smoked-salmon-bagel",
    },
    {
      section: "manha",
      title: "Huevos rancheros",
      subtitle: "20 min",
      protein_note: "~22 g",
      tags: ["mexicano"],
      ingredients: ["tortilhas", "ovos", "salsa", "feijão", "queijo"],
      steps: ["Aquece tortilhas e feijão.", "Frita ovos.", "Monta e cobre com salsa."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes huevos rancheros: https://www.allrecipes.com/recipe/14054/huevos-rancheros/",
    },
    {
      section: "manha",
      title: "Waffles clássicos",
      subtitle: "20 min",
      protein_note: "~10 g",
      tags: ["doce"],
      ingredients: ["massa de waffle", "fruta", "mel"],
      steps: ["Prepara massa.", "Coze na máquina até dourar.", "Serve com fruta."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes waffles: https://www.allrecipes.com/recipe/20513/classic-waffles/",
    },
    {
      section: "manha",
      title: "Cottage bowl",
      subtitle: "3 min",
      protein_note: "~25 g",
      tags: ["sem fogão"],
      ingredients: ["cottage", "fruta", "mel", "sementes"],
      steps: ["Deita cottage.", "Junta fruta, mel e sementes."],
      note: "Baseado em técnicas clássicas · ref. BBC high-protein breakfast: https://www.bbcgoodfood.com/recipes/collection/high-protein-breakfast-recipes",
    },
    {
      section: "manha",
      title: "Wrap ovo e bacon",
      subtitle: "15 min",
      protein_note: "~28 g",
      tags: ["leva-te"],
      ingredients: ["tortilha", "2 ovos", "bacon", "queijo"],
      steps: ["Frita bacon.", "Ovos mexidos.", "Recheia e enrola."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes breakfast wraps: https://www.allrecipes.com/recipe/244949/easy-breakfast-wraps/",
    },
    {
      section: "manha",
      title: "Chia pudding",
      subtitle: "Noite anterior",
      protein_note: "~10 g",
      tags: ["sem fogão"],
      ingredients: ["chia", "leite", "mel", "fruta"],
      steps: ["Mistura chia e leite.", "Mexe após 10 min.", "Frio ≥4 h.", "Serve com fruta."],
      note: "Baseado em técnicas clássicas · ref. BBC chia pudding: https://www.bbcgoodfood.com/recipes/chia-seed-pudding",
    },
    {
      section: "manha",
      title: "Batido proteína caseiro",
      subtitle: "3 min",
      protein_note: "~25 g",
      tags: ["líquido"],
      ingredients: ["banana", "leite", "iogurte grego", "amendoim"],
      steps: ["Tritura tudo 40 s.", "Ajusta com leite."],
      note: "Baseado em técnicas clássicas · ref. BBC smoothies: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "manha",
      title: "Hash browns com ovos",
      subtitle: "25 min",
      protein_note: "~18 g",
      tags: ["frigideira"],
      ingredients: ["batatas raladas", "ovos", "óleo", "sal"],
      steps: ["Seca bem a batata.", "Frita até crocante.", "Serve com ovos fritos."],
      note: "Baseado em técnicas clássicas · ref. Serious Eats hash browns: https://www.seriouseats.com/crispy-hash-browns-recipe",
    },
    {
      section: "manha",
      title: "Wrap PB e banana",
      subtitle: "5 min",
      protein_note: "~12 g",
      tags: ["doce"],
      ingredients: ["wrap", "pasta amendoim", "banana"],
      steps: ["Espalha amendoim.", "Banana em rodelas.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes PB banana: https://www.allrecipes.com/recipe/20979/peanut-butter-and-banana-sandwiches/",
    },
    {
      section: "manha",
      title: "Frittata de forno",
      subtitle: "30 min",
      protein_note: "~24 g",
      tags: ["forno"],
      ingredients: ["6 ovos", "vegetais", "queijo", "azeite"],
      steps: ["Salteia vegetais.", "Mistura com ovos e queijo.", "Forno 190 °C 15–20 min."],
      note: "Baseado em técnicas clássicas · ref. BBC frittata: https://www.bbcgoodfood.com/recipes/basic-frittata-recipe",
    },
    {
      section: "manha",
      title: "Iogurte cacau e amendoim",
      subtitle: "2 min",
      protein_note: "~20 g",
      tags: ["sem fogão"],
      ingredients: ["iogurte grego", "cacau", "pasta amendoim", "mel"],
      steps: ["Mistura tudo até cremoso."],
      note: "Baseado em técnicas clássicas · ref. high-protein bowl: https://www.bbcgoodfood.com/recipes/collection/high-protein-breakfast-recipes",
    },
    {
      section: "manha",
      title: "Tortilha espanhola rápida",
      subtitle: "25 min",
      protein_note: "~20 g",
      tags: ["espanhola"],
      ingredients: ["3 ovos", "batata cozida", "cebola", "azeite"],
      steps: ["Refoga cebola e batata.", "Junta ovos.", "Coze em lume baixo e vira."],
      note: "Baseado em técnicas clássicas · ref. BBC Spanish tortilla: https://www.bbcgoodfood.com/recipes/spanish-tortilla",
    },
    {
      section: "manha",
      title: "Granola caseira",
      subtitle: "30 min",
      protein_note: "~8 g/dose",
      tags: ["meal prep"],
      ingredients: ["aveia", "frutos secos", "mel", "azeite", "canela"],
      steps: ["Mistura e espalha no tabuleiro.", "160 °C 20–25 min.", "Arrefece e guarda."],
      note: "Baseado em técnicas clássicas · ref. BBC granola: https://www.bbcgoodfood.com/recipes/super-healthy-granola",
    },
    {
      section: "manha",
      title: "Ovos escalfados",
      subtitle: "10 min",
      protein_note: "~12 g",
      tags: ["técnica"],
      ingredients: ["ovos frescos", "vinagre", "pão"],
      steps: ["Água a ferver suave com vinagre.", "Deita ovo no remoinho 3–4 min.", "Serve no pão."],
      note: "Baseado em técnicas clássicas · ref. Serious Eats poached eggs: https://www.seriouseats.com/perfect-poached-eggs",
    },
    {
      section: "manha",
      title: "Skyr com frutos vermelhos",
      subtitle: "2 min",
      protein_note: "~20 g",
      tags: ["sem fogão"],
      ingredients: ["skyr", "frutos vermelhos", "mel"],
      steps: ["Deita skyr.", "Cobre com frutos e mel."],
      note: "Baseado em técnicas clássicas · ref. BBC breakfast: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes",
    },
    {
      section: "manha",
      title: "Crepes simples",
      subtitle: "20 min",
      protein_note: "~10 g",
      tags: ["versátil"],
      ingredients: ["farinha", "ovo", "leite", "sal", "manteiga"],
      steps: ["Bate massa lisa.", "Frita finos.", "Recheia doce ou salgado."],
      note: "Baseado em técnicas clássicas · ref. BBC crepes: https://www.bbcgoodfood.com/recipes/easy-crepes",
    },
    {
      section: "manha",
      title: "Ovos no forno com queijo",
      subtitle: "15 min",
      protein_note: "~18 g",
      tags: ["forno"],
      ingredients: ["ovos", "natas", "queijo", "manteiga"],
      steps: ["Unta ramequins.", "Natas + ovos + queijo.", "180 °C 10–12 min."],
      note: "Baseado em técnicas clássicas · ref. NYT baked eggs: https://cooking.nytimes.com/recipes/1013070-baked-eggs",
    },
    {
      section: "manha",
      title: "Tapioca com queijo",
      subtitle: "10 min",
      protein_note: "~15 g",
      tags: ["frigideira"],
      ingredients: ["goma tapioca", "queijo"],
      steps: ["Espalha tapioca na frigideira.", "Quando unir, salpica queijo.", "Dobra."],
      note: "Baseado em técnicas clássicas · ref. TudoGostoso tapioca: https://www.tudogostoso.com.br/receita/29876-tapioca.htm",
    },
    {
      section: "manha",
      title: "Muesli bircher",
      subtitle: "Noite anterior",
      protein_note: "~12 g",
      tags: ["sem fogão"],
      ingredients: ["aveia", "maçã ralada", "iogurte", "mel"],
      steps: ["Mistura e leva ao frio.", "De manhã envolve."],
      note: "Baseado em técnicas clássicas · ref. BBC bircher: https://www.bbcgoodfood.com/recipes/bircher-muesli-apple-banana",
    },
    {
      section: "manha",
      title: "Quesadilla de manhã",
      subtitle: "12 min",
      protein_note: "~22 g",
      tags: ["frigideira"],
      ingredients: ["tortilha", "ovos mexidos", "queijo", "fiambre"],
      steps: ["Recheia.", "Doura dos dois lados.", "Corta."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes breakfast quesadilla: https://www.allrecipes.com/recipe/14250/breakfast-quesadilla/",
    },
    {
      section: "manha",
      title: "Panquecas de banana 3 ingredientes",
      subtitle: "12 min",
      protein_note: "~14 g",
      tags: ["rápido"],
      ingredients: ["1 banana", "2 ovos", "canela"],
      steps: ["Esmaga banana com ovos.", "Frita colheradas em lume baixo.", "Vira com cuidado."],
      note: "Baseado em técnicas clássicas · ref. BBC banana pancakes: https://www.bbcgoodfood.com/recipes/banana-pancakes",
    },
    {
      section: "manha",
      title: "Tosta ricotta e mel",
      subtitle: "5 min",
      protein_note: "~14 g",
      tags: ["simples"],
      ingredients: ["pão", "ricotta", "mel", "nozes"],
      steps: ["Tosta pão.", "Ricotta + mel + nozes."],
      note: "Baseado em técnicas clássicas · ref. BBC ricotta toast: https://www.bbcgoodfood.com/recipes/ricotta-toast",
    },
    {
      section: "manha",
      title: "Ovos mexidos com atum",
      subtitle: "8 min",
      protein_note: "~32 g",
      tags: ["lata"],
      ingredients: ["3 ovos", "atum", "manteiga", "queijo"],
      steps: ["Refoga atum.", "Junta ovos.", "Queijo no fim."],
      note: "Baseado em técnicas clássicas · ref. adaptação Serious Eats: https://www.seriouseats.com/fluffy-scrambled-eggs",
    },
    {
      section: "manha",
      title: "Croque-madame simples",
      subtitle: "15 min",
      protein_note: "~28 g",
      tags: ["confortável"],
      ingredients: ["pão", "fiambre", "queijo", "ovo", "manteiga"],
      steps: ["Monta sandes e tosta.", "Ovo estrelado em cima."],
      note: "Baseado em técnicas clássicas · ref. BBC croque-madame: https://www.bbcgoodfood.com/recipes/croque-madame",
    },
    {
      section: "manha",
      title: "Overnight oats de cacau",
      subtitle: "Noite anterior",
      protein_note: "~12 g",
      tags: ["sem fogão"],
      ingredients: ["aveia", "cacau", "leite", "mel", "banana"],
      steps: ["Mistura e refrigerar.", "Banana de manhã."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes overnight oats: https://www.allrecipes.com/recipe/240406/overnight-oats/",
    },
    {
      section: "manha",
      title: "Bacon, egg & cheese",
      subtitle: "15 min",
      protein_note: "~30 g",
      tags: ["clássico"],
      ingredients: ["pão", "bacon", "ovo", "queijo"],
      steps: ["Frita bacon e ovo.", "Monta e derrete queijo."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes BEC: https://www.allrecipes.com/recipe/212961/bacon-egg-and-cheese-sandwich/",
    },
    {
      section: "manha",
      title: "Pão tomate azeite e ovo",
      subtitle: "12 min",
      protein_note: "~16 g",
      tags: ["mediterrânico"],
      ingredients: ["pão", "tomate", "azeite", "ovos", "orégãos"],
      steps: ["Esfrega tomate no pão.", "Azeite e ovos.", "Orégãos."],
      note: "Baseado em técnicas clássicas · ref. BBC pan con tomate: https://www.bbcgoodfood.com/recipes/pan-con-tomate",
    },
    {
      section: "manha",
      title: "Muffins banana e aveia",
      subtitle: "25 min",
      protein_note: "~6 g/un",
      tags: ["forno"],
      ingredients: ["2 bananas", "2 ovos", "aveia", "fermento", "canela"],
      steps: ["Esmaga e mistura.", "Formas de muffin.", "180 °C 18–22 min."],
      note: "Baseado em técnicas clássicas · ref. BBC banana oat muffins: https://www.bbcgoodfood.com/recipes/banana-oat-muffins",
    },
    {
      section: "manha",
      title: "Ovos com espinafres",
      subtitle: "12 min",
      protein_note: "~20 g",
      tags: ["verde"],
      ingredients: ["ovos", "espinafres", "alho", "azeite"],
      steps: ["Murcha espinafres com alho.", "Junta ovos mexidos."],
      note: "Baseado em técnicas clássicas · ref. adaptação scramble: https://www.seriouseats.com/fluffy-scrambled-eggs",
    },
    {
      section: "manha",
      title: "Breakfast casserole",
      subtitle: "Forno · 45 min",
      protein_note: "~22 g",
      tags: ["forno", "multidão"],
      ingredients: ["ovos", "hash browns", "salsicha ou fiambre", "queijo", "leite"],
      steps: ["Mistura tudo num tabuleiro.", "180 °C cerca de 40 min até firme."],
      note: "Baseado em técnicas clássicas · ref. NYT breakfast casserole: https://cooking.nytimes.com/recipes/1024346-breakfast-casserole",
    },
    {
      section: "manha",
      title: "Overnight French toast",
      subtitle: "Preparar à noite · forno",
      protein_note: "~14 g",
      tags: ["forno"],
      ingredients: ["pão brioche", "ovos", "leite", "açúcar mascavado", "canela"],
      steps: ["Dispõe pão num tabuleiro.", "Bate ovos+leite+especiarias e rega.", "Frio durante a noite.", "Forno até dourar."],
      note: "Baseado em técnicas clássicas · ref. NYT overnight French toast: https://cooking.nytimes.com/recipes/1019102-overnight-french-toast",
    },
    {
      section: "manha",
      title: "Bagel hummus e ovo cozido",
      subtitle: "10 min",
      protein_note: "~18 g",
      tags: ["leva-te"],
      ingredients: ["wrap", "hummus", "ovos cozidos", "alface"],
      steps: ["Hummus no wrap.", "Ovo esmagado.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. BBC wraps: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "manha",
      title: "Salsichas e ovos",
      subtitle: "15 min",
      protein_note: "~25 g",
      tags: ["refeição"],
      ingredients: ["salsichas", "ovos", "pão"],
      steps: ["Frita salsichas.", "Ovos na mesma frigideira.", "Pão tostado."],
      note: "Baseado em técnicas clássicas · ref. clássico diner: https://www.allrecipes.com/recipe/16354/breakfast-burritos/",
    },
    {
      section: "manha",
      title: "Batata-doce assada com iogurte",
      subtitle: "40 min",
      protein_note: "~12 g",
      tags: ["forno"],
      ingredients: ["batata-doce", "iogurte grego", "canela"],
      steps: ["Assa batata 200 °C ~40 min.", "Abre e cobre com iogurte."],
      note: "Baseado em técnicas clássicas · ref. BBC sweet potato: https://www.bbcgoodfood.com/recipes/collection/sweet-potato-recipes",
    },
    {
      section: "manha",
      title: "Pão perdido salgado",
      subtitle: "12 min",
      protein_note: "~18 g",
      tags: ["frigideira"],
      ingredients: ["pão", "ovo", "leite", "queijo", "sal"],
      steps: ["Molha pão em ovo+leite.", "Frita.", "Derrete queijo em cima."],
      note: "Baseado em técnicas clássicas · ref. adaptação French toast: https://www.allrecipes.com/recipe/7016/french-toast-i/",
    },
    {
      section: "manha",
      title: "Bowl fruta iogurte sementes",
      subtitle: "5 min",
      protein_note: "~15 g",
      tags: ["leve"],
      ingredients: ["fruta", "iogurte", "sementes", "mel"],
      steps: ["Monta em camadas."],
      note: "Baseado em técnicas clássicas · ref. BBC breakfast: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes",
    },
    {
      section: "manha",
      title: "Migas de ovo com pão",
      subtitle: "15 min",
      protein_note: "~18 g",
      tags: ["aproveitamento"],
      ingredients: ["pão do dia anterior", "ovos", "alho", "azeite", "salsa"],
      steps: ["Refoga alho e pão em cubos.", "Junta ovos e mexe.", "Salsa."],
      note: "Baseado em técnicas clássicas · ref. migas ibéricas / bread scramble: https://www.bbcgoodfood.com/recipes/collection/egg-recipes",
    },
    {
      section: "manha",
      title: "Café da manhã português simples",
      subtitle: "10 min",
      protein_note: "~16 g",
      tags: ["local"],
      ingredients: ["pão", "queijo", "fiambre", "manteiga", "café ou chá", "fruta"],
      steps: ["Tosta pão com manteiga.", "Queijo e fiambre.", "Fruta a acompanhar."],
      note: "Baseado em técnicas clássicas · ref. clássico PT: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "Patê de atum clássico",
      subtitle: "Sandes fria",
      protein_note: "atum",
      tags: ["mala térmica"],
      ingredients: ["atum escorrido", "maionese", "ovo cozido opcional", "sal", "pimenta", "pão"],
      steps: ["Escorre e desfaz o atum.", "Mistura maionese até cremoso.", "Junta ovo picado se usares.", "Espalha no pão. Mantém frio."],
      note: "Baseado em técnicas clássicas · ref. clássico PT sandes atum: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "California turkey club wrap",
      subtitle: "15 min",
      protein_note: "~28 g",
      tags: ["wrap"],
      ingredients: ["tortilha", "peru", "bacon", "abacate", "tomate", "alface", "maionese"],
      steps: ["Coze bacon.", "Espalha maionese na tortilha.", "Empilha peru, bacon, abacate, tomate e alface.", "Enrolha apertado."],
      note: "Baseado em técnicas clássicas · ref. Tastes Lovely turkey wrap: https://www.tasteslovely.com/california-turkey-club-wrap/",
    },
    {
      section: "praia",
      title: "Wrap mediterrânico de frango",
      subtitle: "Tzatziki + feta",
      protein_note: "~30 g",
      tags: ["fria"],
      ingredients: ["frango desfiado", "tzatziki", "feta", "pepino", "tomate", "wrap"],
      steps: ["Mistura frango com limão e azeite.", "Espalha tzatziki.", "Recheia com vegetais e feta.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. Mediterranean picnic wraps: https://lifeandsprinkles.com/mediterranean-picnic-wraps/",
    },
    {
      section: "praia",
      title: "Sandes de ovo e maionese",
      subtitle: "Clássica britânica",
      protein_note: "~20 g",
      tags: ["fria"],
      ingredients: ["4 ovos", "maionese", "pão mole", "sal", "pimenta"],
      steps: ["Coze ovos 9–10 min.", "Esmaga com maionese.", "Espalha no pão."],
      note: "Baseado em técnicas clássicas · ref. clássico egg mayo: https://www.bbcgoodfood.com/recipes/egg-mayonnaise-sandwiches",
    },
    {
      section: "praia",
      title: "Bagel salmão e cream cheese",
      subtitle: "5 min",
      protein_note: "~25 g",
      tags: ["sem fogão"],
      ingredients: ["salmão fumado", "cream cheese", "wrap", "limão"],
      steps: ["Cream cheese.", "Salmão.", "Limão; enrola. Mantém frio."],
      note: "Baseado em técnicas clássicas · ref. BBC smoked salmon: https://www.bbcgoodfood.com/recipes/smoked-salmon-bagel",
    },
    {
      section: "praia",
      title: "Chicken salad wrap",
      subtitle: "Frango cremoso",
      protein_note: "~30 g",
      tags: ["preparar à noite"],
      ingredients: ["frango desfiado", "maionese ou iogurte", "limão", "wrap", "alface"],
      steps: ["Mistura frango com maionese e limão.", "Recheia wrap com alface.", "Embrulha frio."],
      note: "Baseado em técnicas clássicas · ref. picnic chicken wrap: https://picklestravel.com/5-rotisserie-chicken-wrap-sandwich-recipes-for-summer/",
    },
    {
      section: "praia",
      title: "Sandes de frango assado",
      subtitle: "Compra pronto",
      protein_note: "~28 g",
      tags: ["rápido"],
      ingredients: ["frango assado", "maionese", "pão", "alface"],
      steps: ["Desfia frango.", "Mistura com maionese.", "Monta sandes."],
      note: "Baseado em técnicas clássicas · ref. rotisserie chicken sandwich: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Wrap de hummus e vegetais",
      subtitle: "Vegetariano",
      protein_note: "~12 g",
      tags: ["frio"],
      ingredients: ["wrap", "hummus", "pepino", "cenoura", "pimento", "rúcula"],
      steps: ["Espalha hummus.", "Juliana de vegetais.", "Enrolha bem."],
      note: "Baseado em técnicas clássicas · ref. BBC hummus wrap: https://www.bbcgoodfood.com/recipes/hummus-wrap",
    },
    {
      section: "praia",
      title: "Sandes BLT",
      subtitle: "Bacon alface tomate",
      protein_note: "~22 g",
      tags: ["clássico"],
      ingredients: ["bacon", "alface", "tomate", "maionese", "pão"],
      steps: ["Frita bacon crocante; arrefece.", "Monta com maionese, alface e tomate."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes BLT: https://www.allrecipes.com/recipe/14497/blt-sandwich/",
    },
    {
      section: "praia",
      title: "Pinwheels de fiambre e cream cheese",
      subtitle: "Partilhável",
      protein_note: "~18 g",
      tags: ["picnic"],
      ingredients: ["wraps", "cream cheese", "fiambre", "queijo"],
      steps: ["Espalha cream cheese.", "Cobre com fiambre e queijo.", "Enrolha apertado; corta em rodelas."],
      note: "Baseado em técnicas clássicas · ref. pinwheel sandwiches: https://www.allrecipes.com/recipe/23694/tortilla-pinwheels/",
    },
    {
      section: "praia",
      title: "Sandes de queijo grelhado fria/morna",
      subtitle: "Comfort",
      protein_note: "~18 g",
      tags: ["quente ou morna"],
      ingredients: ["pão", "queijo", "manteiga"],
      steps: ["Manteiga por fora.", "Queijo dentro; doura na frigideira.", "Pode ir morna na mala térmica."],
      note: "Baseado em técnicas clássicas · ref. grilled cheese: https://www.allrecipes.com/recipe/23891/grilled-cheese-sandwich/",
    },
    {
      section: "praia",
      title: "Pasta salad de atum",
      subtitle: "Massa fria",
      protein_note: "~25 g",
      tags: ["mala térmica"],
      ingredients: ["massa curta", "atum", "milho", "maionese ou azeite", "cebola"],
      steps: ["Coze e arrefece a massa.", "Mistura atum e restantes.", "Tempera e leva frio."],
      note: "Baseado em técnicas clássicas · ref. tuna pasta salad: https://www.allrecipes.com/recipe/16726/tuna-pasta-salad/",
    },
    {
      section: "praia",
      title: "Sandes caprese",
      subtitle: "Mozzarella tomate manjericão",
      protein_note: "~16 g",
      tags: ["vegetariano"],
      ingredients: ["ciabatta", "mozzarella", "tomate", "manjericão", "azeite"],
      steps: ["Monta em camadas.", "Azeite e sal.", "Embrulha."],
      note: "Baseado em técnicas clássicas · ref. caprese sandwich: https://www.bbcgoodfood.com/recipes/caprese-sandwich",
    },
    {
      section: "praia",
      title: "Wrap de peru e abacate",
      subtitle: "15 min",
      protein_note: "~26 g",
      tags: ["wrap"],
      ingredients: ["peru", "abacate", "wrap", "alface", "limão"],
      steps: ["Esmaga abacate com limão.", "Espalha; põe peru e alface.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. turkey avocado wrap: https://mandiofthemountains.com/turkey-wrap-with-bacon-and-avocado/",
    },
    {
      section: "praia",
      title: "Sandes de sardinha e ovo",
      subtitle: "Lata PT",
      protein_note: "~28 g",
      tags: ["lata"],
      ingredients: ["sardinhas", "ovos cozidos", "maionese ou azeite", "pão", "limão"],
      steps: ["Esmaga sardinha e ovo.", "Mistura gordura/limão.", "Espalha no pão."],
      note: "Baseado em técnicas clássicas · ref. clássico PT: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "Bagel Caesar de frango",
      subtitle: "Fria",
      protein_note: "~28 g",
      tags: ["wrap"],
      ingredients: ["frango", "alface romana", "parmesão", "molho Caesar", "wrap"],
      steps: ["Mistura alface com molho.", "Junta frango e parmesão.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. chicken Caesar wrap: https://www.bbcgoodfood.com/recipes/chicken-caesar-wrap",
    },
    {
      section: "praia",
      title: "Sandes de roast beef e mostarda",
      subtitle: "Clássica",
      protein_note: "~30 g",
      tags: ["fria"],
      ingredients: ["roast beef", "mostarda", "rúcula", "pão"],
      steps: ["Mostarda no pão.", "Carne e rúcula.", "Fecha."],
      note: "Baseado em técnicas clássicas · ref. deli roast beef: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Bowl de couscous frio",
      subtitle: "Para mala",
      protein_note: "~15 g",
      tags: ["frio"],
      ingredients: ["couscous", "grão", "pepino", "tomate", "azeite", "limão"],
      steps: ["Hidrata couscous.", "Mistura vegetais e grão.", "Tempera azeite-limão."],
      note: "Baseado em técnicas clássicas · ref. couscous salad: https://www.bbcgoodfood.com/recipes/moroccan-couscous",
    },
    {
      section: "praia",
      title: "Sandes club clássico",
      subtitle: "Triplo andar",
      protein_note: "~32 g",
      tags: ["clássico"],
      ingredients: ["pão tostado", "frango ou peru", "bacon", "alface", "tomate", "maionese"],
      steps: ["Tosta pão.", "Monta 3 andares.", "Espeta e corta triângulos."],
      note: "Baseado em técnicas clássicas · ref. club sandwich: https://www.allrecipes.com/recipe/14496/club-sandwich/",
    },
    {
      section: "praia",
      title: "Wrap buffalo chicken",
      subtitle: "Picante suave",
      protein_note: "~30 g",
      tags: ["wrap"],
      ingredients: ["frango", "molho buffalo", "ranch ou iogurte", "wrap", "alface"],
      steps: ["Mistura frango com buffalo.", "Espalha ranch.", "Recheia e enrola."],
      note: "Baseado em técnicas clássicas · ref. buffalo chicken wrap: https://picklestravel.com/5-rotisserie-chicken-wrap-sandwich-recipes-for-summer/",
    },
    {
      section: "praia",
      title: "Sandes de queijo fresco e mel",
      subtitle: "Mole",
      protein_note: "~14 g",
      tags: ["soft"],
      ingredients: ["queijo fresco", "mel", "pão de leite", "nozes opcional"],
      steps: ["Espalha queijo.", "Mel e nozes.", "Fecha."],
      note: "Baseado em técnicas clássicas · ref. soft picnic: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Insalata di riso",
      subtitle: "Arroz frio italiano",
      protein_note: "~12 g",
      tags: ["frio"],
      ingredients: ["arroz", "atum", "azeitonas", "pimentos", "azeite"],
      steps: ["Coze arroz; arrefece.", "Mistura ingredientes.", "Tempera."],
      note: "Baseado em técnicas clássicas · ref. insalata di riso: https://www.bbcgoodfood.com/recipes/collection/rice-salad-recipes",
    },
    {
      section: "praia",
      title: "Wrap de feijão preto e milho",
      subtitle: "Vegetariano",
      protein_note: "~16 g",
      tags: ["wrap"],
      ingredients: ["feijão preto", "milho", "arroz frio", "salsa", "wrap", "queijo"],
      steps: ["Mistura feijão, milho e arroz.", "Recheia com salsa e queijo."],
      note: "Baseado em técnicas clássicas · ref. southwestern wrap: https://picklestravel.com/5-rotisserie-chicken-wrap-sandwich-recipes-for-summer/",
    },
    {
      section: "praia",
      title: "Sandes de atum e ovo (dupla)",
      subtitle: "Patê reforçado",
      protein_note: "~32 g",
      tags: ["fria"],
      ingredients: ["atum", "ovos", "maionese", "pão"],
      steps: ["Mistura tudo até patê.", "Espalha e embala frio."],
      note: "Baseado em técnicas clássicas · ref. clássico: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "Pita de falafel e tahini",
      subtitle: "Vegetariano",
      protein_note: "~18 g",
      tags: ["frio/morno"],
      ingredients: ["falafel", "pita", "alface", "tomate", "tahini ou iogurte"],
      steps: ["Aquece pita.", "Recheia falafel e vegetais.", "Molho por cima."],
      note: "Baseado em técnicas clássicas · ref. BBC falafel pittas: https://www.bbcgoodfood.com/recipes/falafel-burgers",
    },
    {
      section: "praia",
      title: "Sandes de mortadela e queijo",
      subtitle: "Italiana simples",
      protein_note: "~20 g",
      tags: ["fria"],
      ingredients: ["ciabatta", "mortadela", "queijo", "azeite"],
      steps: ["Abre pão.", "Mortadela e queijo.", "Azeite."],
      note: "Baseado em técnicas clássicas · ref. italian deli: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Wrap de atum e milho",
      subtitle: "Rápido",
      protein_note: "~26 g",
      tags: ["lata"],
      ingredients: ["atum", "milho", "maionese", "wrap"],
      steps: ["Mistura.", "Espalha e enrola."],
      note: "Baseado em técnicas clássicas · ref. tuna wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Sandes de pesto frango e mozzarella",
      subtitle: "Morna ou fria",
      protein_note: "~28 g",
      tags: ["wrap/sandes"],
      ingredients: ["frango", "pesto", "mozzarella", "tomate", "ciabatta"],
      steps: ["Pesto no pão.", "Frango, queijo e tomate.", "Opcional: aquecer para derreter."],
      note: "Baseado em técnicas clássicas · ref. pesto chicken sandwich: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Tabuleh para picnic",
      subtitle: "Salada de salsa",
      protein_note: "~6 g",
      tags: ["leve"],
      ingredients: ["bulgur ou couscous", "salsa", "tomate", "limão", "azeite"],
      steps: ["Hidrata cereal.", "Mistura erva e tomate.", "Tempera."],
      note: "Baseado em técnicas clássicas · ref. tabbouleh: https://www.bbcgoodfood.com/recipes/tabbouleh",
    },
    {
      section: "praia",
      title: "Sandes de camembert e doce de figo",
      subtitle: "Gourmet picnic",
      protein_note: "~16 g",
      tags: ["fria"],
      ingredients: ["baguete", "camembert", "doce figo ou mel", "rúcula"],
      steps: ["Abre baguete.", "Queijo + doce + rúcula."],
      note: "Baseado em técnicas clássicas · ref. cheese picnic loaf: https://www.bbcgoodfood.com/recipes/collection/picnic-recipes",
    },
    {
      section: "praia",
      title: "Wrap de ovo cozido e abacate",
      subtitle: "Sem fogão (se ovos prontos)",
      protein_note: "~22 g",
      tags: ["frio"],
      ingredients: ["ovos cozidos", "abacate", "wrap", "sal", "limão"],
      steps: ["Esmaga abacate e ovo.", "Tempera.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. egg avocado wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Sandes de carne assada fria",
      subtitle: "Sobra do jantar",
      protein_note: "~30 g",
      tags: ["fria"],
      ingredients: ["carne assada fatiada", "mostarda", "pão", "pickles"],
      steps: ["Mostarda no pão.", "Carne e pickles."],
      note: "Baseado em técnicas clássicas · ref. leftover roast sandwich: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Pasta pesto fria",
      subtitle: "Massa de leve",
      protein_note: "~14 g",
      tags: ["frio"],
      ingredients: ["massa", "pesto", "tomate cherry", "mozzarella cereja"],
      steps: ["Coze e arrefece massa.", "Envolve pesto e extras."],
      note: "Baseado em técnicas clássicas · ref. pesto pasta salad: https://www.bbcgoodfood.com/recipes/pesto-pasta-salad",
    },
    {
      section: "praia",
      title: "Sandes de pepino e cream cheese",
      subtitle: "Inglesa leve",
      protein_note: "~8 g",
      tags: ["leve"],
      ingredients: ["pão de forma sem casca", "cream cheese", "pepino", "pimenta"],
      steps: ["Cream cheese.", "Pepino fino.", "Corta em retângulos."],
      note: "Baseado em técnicas clássicas · ref. cucumber sandwiches: https://www.bbcgoodfood.com/recipes/cucumber-sandwiches",
    },
    {
      section: "praia",
      title: "Wrap grego de frango",
      subtitle: "Feta + pepino",
      protein_note: "~28 g",
      tags: ["fria"],
      ingredients: ["frango", "feta", "pepino", "azeitonas", "wrap", "iogurte"],
      steps: ["Iogurte no wrap.", "Recheia frango e vegetais."],
      note: "Baseado em técnicas clássicas · ref. Greek chicken wrap: https://picklestravel.com/5-rotisserie-chicken-wrap-sandwich-recipes-for-summer/",
    },
    {
      section: "praia",
      title: "Sandes de atum Niçoise estilo",
      subtitle: "Ovo azeitona",
      protein_note: "~28 g",
      tags: ["fria"],
      ingredients: ["atum", "ovo", "azeitonas", "alface", "pão", "azeite"],
      steps: ["Monta camadas.", "Azeite e pimenta."],
      note: "Baseado em técnicas clássicas · ref. niçoise sandwich: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Mini baguetes fiambre queijo",
      subtitle: "Várias unidades",
      protein_note: "~20 g",
      tags: ["partilhável"],
      ingredients: ["baguete", "fiambre", "queijo", "manteiga"],
      steps: ["Corta baguete.", "Unta e recheia."],
      note: "Baseado em técnicas clássicas · ref. clássico picnic: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "Wrap de ricotta e tomate seco",
      subtitle: "Soft",
      protein_note: "~16 g",
      tags: ["frio"],
      ingredients: ["ricotta", "tomate seco", "rúcula", "wrap", "azeite"],
      steps: ["Espalha ricotta.", "Tomate e rúcula.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. italian wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Salada de grão para praia",
      subtitle: "Proteína vegetal",
      protein_note: "~14 g",
      tags: ["frio"],
      ingredients: ["grão-de-bico", "cebola roxa", "salsa", "azeite", "limão"],
      steps: ["Escorre grão.", "Mistura tudo.", "Leva frio."],
      note: "Baseado em técnicas clássicas · ref. chickpea salad: https://www.bbcgoodfood.com/recipes/collection/chickpea-recipes",
    },
    {
      section: "praia",
      title: "Sandes de pastrami e mostarda",
      subtitle: "Deli",
      protein_note: "~30 g",
      tags: ["fria"],
      ingredients: ["pastrami ou fiambre fumado", "mostarda", "pão de centeio", "picles"],
      steps: ["Mostarda.", "Carne e picles."],
      note: "Baseado em técnicas clássicas · ref. deli pastrami: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Wrap de atum picante",
      subtitle: "Sriracha mayo",
      protein_note: "~26 g",
      tags: ["wrap"],
      ingredients: ["atum", "maionese", "sriracha", "wrap", "alface"],
      steps: ["Mistura atum com maionese picante.", "Recheia e enrola."],
      note: "Baseado em técnicas clássicas · ref. spicy tuna wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Sandes de beringela assada",
      subtitle: "Vegetariano",
      protein_note: "~10 g",
      tags: ["fria/morna"],
      ingredients: ["beringela assada", "pão", "queijo fresco", "azeite"],
      steps: ["Assa beringela antecipadamente.", "Monta sandes fria."],
      note: "Baseado em técnicas clássicas · ref. aubergine sandwich: https://www.bbcgoodfood.com/recipes/collection/sandwich-recipes",
    },
    {
      section: "praia",
      title: "Quinoa salad box",
      subtitle: "Para caixa",
      protein_note: "~16 g",
      tags: ["frio"],
      ingredients: ["quinoa", "feijão", "pepino", "feta", "limão"],
      steps: ["Coze quinoa; arrefece.", "Mistura restantes.", "Tempera."],
      note: "Baseado em técnicas clássicas · ref. quinoa salad: https://www.bbcgoodfood.com/recipes/collection/quinoa-recipes",
    },
    {
      section: "praia",
      title: "Sandes de ovo cozido e mostarda",
      subtitle: "Simples",
      protein_note: "~18 g",
      tags: ["fria"],
      ingredients: ["ovos", "mostarda", "maionese", "pão"],
      steps: ["Esmaga ovos com mostarda e maionese.", "Espalha."],
      note: "Baseado em técnicas clássicas · ref. egg mustard sandwich: https://www.bbcgoodfood.com/recipes/egg-mayonnaise-sandwiches",
    },
    {
      section: "praia",
      title: "Wrap de camarão e cocktail",
      subtitle: "Se tiveres frio",
      protein_note: "~24 g",
      tags: ["fria"],
      ingredients: ["camarão cozido", "molho cocktail", "alface", "wrap"],
      steps: ["Mistura camarão com molho.", "Alface e enrola. Mantém muito frio."],
      note: "Baseado em técnicas clássicas · ref. prawn cocktail wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Sandes de patê de frango",
      subtitle: "Cremosa",
      protein_note: "~26 g",
      tags: ["fria"],
      ingredients: ["frango", "maionese", "curry em pó opcional", "pão"],
      steps: ["Desfia e mistura.", "Espalha."],
      note: "Baseado em técnicas clássicas · ref. coronation/chicken mayo: https://www.bbcgoodfood.com/recipes/coronation-chicken",
    },
    {
      section: "praia",
      title: "Focaccia recheada para picnic",
      subtitle: "Partilhar",
      protein_note: "~18 g",
      tags: ["partilhável"],
      ingredients: ["focaccia", "queijo", "presunto ou vegetais grelhados"],
      steps: ["Abre focaccia.", "Recheia.", "Corta em quadrados."],
      note: "Baseado em técnicas clássicas · ref. picnic focaccia: https://www.bbcgoodfood.com/recipes/collection/picnic-recipes",
    },
    {
      section: "praia",
      title: "Wrap de lentilhas e feta",
      subtitle: "Vegetariano",
      protein_note: "~18 g",
      tags: ["frio"],
      ingredients: ["lentilhas cozidas", "feta", "pepino", "wrap", "azeite"],
      steps: ["Mistura lentilhas com feta e pepino.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. lentil wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "praia",
      title: "Sandes mista portuguesa",
      subtitle: "Clássico café",
      protein_note: "~22 g",
      tags: ["fria"],
      ingredients: ["pão de forma", "fiambre", "queijo", "manteiga"],
      steps: ["Manteiga.", "Fiambre e queijo.", "Opcional: tosta e leva morna."],
      note: "Baseado em técnicas clássicas · ref. clássico PT: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "praia",
      title: "Caixa de antipasti",
      subtitle: "Sem sandes",
      protein_note: "~20 g",
      tags: ["picnic"],
      ingredients: ["queijos", "fiambre", "azeitonas", "pão", "fruta"],
      steps: ["Dispõe num recipiente.", "Pão à parte.", "Mantém fresco."],
      note: "Baseado em técnicas clássicas · ref. antipasti picnic: https://www.bbcgoodfood.com/recipes/collection/picnic-recipes",
    },
    {
      section: "lanches",
      title: "Ovos cozidos com sal",
      subtitle: "Batch",
      protein_note: "~6 g/ovo",
      tags: ["soft"],
      ingredients: ["ovos", "sal"],
      steps: ["Coze 9–10 min.", "Água fria.", "Sal na hora."],
      note: "Baseado em técnicas clássicas · ref. meal prep eggs: https://www.seriouseats.com/hard-boiled-eggs",
    },
    {
      section: "lanches",
      title: "Iogurte grego com mel",
      subtitle: "Colher",
      protein_note: "~15–20 g",
      tags: ["soft"],
      ingredients: ["iogurte grego", "mel"],
      steps: ["Abre e rega com mel."],
      note: "Baseado em técnicas clássicas · ref. BBC breakfast: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes",
    },
    {
      section: "lanches",
      title: "Smoothie banana amendoim",
      subtitle: "Bebível",
      protein_note: "~20 g",
      tags: ["líquido"],
      ingredients: ["banana", "leite", "pasta amendoim"],
      steps: ["Tritura até liso.", "Garrafa fria."],
      note: "Baseado em técnicas clássicas · ref. BBC smoothies: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "lanches",
      title: "Queijo fresco no pão de leite",
      subtitle: "Soft",
      protein_note: "~14 g",
      tags: ["soft"],
      ingredients: ["queijo fresco", "pão de leite"],
      steps: ["Espalha e come."],
      note: "Baseado em técnicas clássicas · ref. clássico: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "lanches",
      title: "Hummus com cenoura",
      subtitle: "Dip",
      protein_note: "~8 g",
      tags: ["soft"],
      ingredients: ["hummus", "cenoura ou pita"],
      steps: ["Mergulha ou espalma na pita."],
      note: "Baseado em técnicas clássicas · ref. BBC hummus: https://www.bbcgoodfood.com/recipes/best-hummus",
    },
    {
      section: "lanches",
      title: "Trail mix caseiro",
      subtitle: "Saco",
      protein_note: "~8 g",
      tags: ["leva-te"],
      ingredients: ["frutos secos", "passas", "chocolate negro opcional"],
      steps: ["Mistura e porciona em sacos."],
      note: "Baseado em técnicas clássicas · ref. trail mix: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Edamame com flor de sal",
      subtitle: "5 min",
      protein_note: "~12 g",
      tags: ["soft"],
      ingredients: ["edamame", "sal"],
      steps: ["Coze ou aquece.", "Sal por cima."],
      note: "Baseado em técnicas clássicas · ref. edamame snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Queijo e bolachas de água e sal",
      subtitle: "Clássico",
      protein_note: "~12 g",
      tags: ["simples"],
      ingredients: ["queijo", "bolachas"],
      steps: ["Monta na hora."],
      note: "Baseado em técnicas clássicas · ref. cheese crackers: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Energy balls de tâmaras",
      subtitle: "Sem forno",
      protein_note: "~5 g/2",
      tags: ["sem fogão"],
      ingredients: ["tâmaras", "aveia", "pasta amendoim", "cacau"],
      steps: ["Tritura ou amassa.", "Bola e refrigerar."],
      note: "Baseado em técnicas clássicas · ref. energy balls: https://www.bbcgoodfood.com/recipes/energy-balls",
    },
    {
      section: "lanches",
      title: "Skyr com fruta",
      subtitle: "Colher",
      protein_note: "~20 g",
      tags: ["soft"],
      ingredients: ["skyr", "fruta", "mel"],
      steps: ["Mistura na taça."],
      note: "Baseado em técnicas clássicas · ref. high protein snack: https://www.bbcgoodfood.com/recipes/collection/high-protein-breakfast-recipes",
    },
    {
      section: "lanches",
      title: "Pão de leite com manteiga de amendoim",
      subtitle: "Macio",
      protein_note: "~12 g",
      tags: ["soft"],
      ingredients: ["pão de leite", "pasta amendoim"],
      steps: ["Espalha generoso."],
      note: "Baseado em técnicas clássicas · ref. PB bread: https://www.allrecipes.com/recipe/20979/peanut-butter-and-banana-sandwiches/",
    },
    {
      section: "lanches",
      title: "Pepino com cream cheese",
      subtitle: "Leve",
      protein_note: "~6 g",
      tags: ["leve"],
      ingredients: ["pepino", "cream cheese", "ervas"],
      steps: ["Espalma cream cheese em rodelas ou barcos de pepino."],
      note: "Baseado em técnicas clássicas · ref. cucumber boats: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Batido de chocolate e banana",
      subtitle: "3 min",
      protein_note: "~15 g",
      tags: ["líquido"],
      ingredients: ["banana", "leite", "cacau", "iogurte"],
      steps: ["Tritura."],
      note: "Baseado em técnicas clássicas · ref. chocolate banana smoothie: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "lanches",
      title: "Torradas de grão (airfryer/forno)",
      subtitle: "Crocante",
      protein_note: "~8 g",
      tags: ["forno"],
      ingredients: ["grão-de-bico", "azeite", "paprika", "sal"],
      steps: ["Seca grão.", "Tempera.", "Tosta 20–25 min 200 °C."],
      note: "Baseado em técnicas clássicas · ref. roasted chickpeas: https://www.bbcgoodfood.com/recipes/roasted-chickpeas",
    },
    {
      section: "lanches",
      title: "Queijo cottage com tomate cherry",
      subtitle: "Salgado",
      protein_note: "~18 g",
      tags: ["soft"],
      ingredients: ["cottage", "tomate", "azeite", "sal"],
      steps: ["Mistura na taça."],
      note: "Baseado em técnicas clássicas · ref. savory cottage: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Maçã com pasta de amendoim",
      subtitle: "2 min",
      protein_note: "~8 g",
      tags: ["rápido"],
      ingredients: ["maçã", "pasta amendoim"],
      steps: ["Fatias + dip."],
      note: "Baseado em técnicas clássicas · ref. apple PB: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Wrap mini de peru",
      subtitle: "Meia dose",
      protein_note: "~16 g",
      tags: ["leva-te"],
      ingredients: ["wrap pequeno", "peru", "queijo"],
      steps: ["Enrolha apertado; corta ao meio."],
      note: "Baseado em técnicas clássicas · ref. mini wrap: https://www.bbcgoodfood.com/recipes/collection/wrap-recipes",
    },
    {
      section: "lanches",
      title: "Iogurte gelo / frozen yogurt rápido",
      subtitle: "Congelador",
      protein_note: "~12 g",
      tags: ["doce"],
      ingredients: ["iogurte", "fruta congelada", "mel"],
      steps: ["Tritura iogurte com fruta congelada."],
      note: "Baseado em técnicas clássicas · ref. frozen yogurt: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Tosta de atum rápida",
      subtitle: "10 min",
      protein_note: "~20 g",
      tags: ["quente"],
      ingredients: ["pão", "atum", "queijo"],
      steps: ["Atum no pão.", "Queijo em cima; gratinar ou micro-ondas."],
      note: "Baseado em técnicas clássicas · ref. tuna melt mini: https://www.allrecipes.com/recipe/16345/tuna-melt/",
    },
    {
      section: "lanches",
      title: "Cenoura e hummus picante",
      subtitle: "Dip",
      protein_note: "~8 g",
      tags: ["soft"],
      ingredients: ["hummus", "harissa ou pimenta", "cenoura"],
      steps: ["Mistura pimenta no hummus.", "Serve com cenoura."],
      note: "Baseado em técnicas clássicas · ref. hummus snack: https://www.bbcgoodfood.com/recipes/best-hummus",
    },
    {
      section: "lanches",
      title: "Banana com chocolate negro",
      subtitle: "2 min",
      protein_note: "~4 g",
      tags: ["doce"],
      ingredients: ["banana", "chocolate 70%"],
      steps: ["Banana + quadrados de chocolate."],
      note: "Baseado em técnicas clássicas · ref. simple snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Pipocas caseiras",
      subtitle: "Panela",
      protein_note: "~4 g",
      tags: ["leve"],
      ingredients: ["milho pipoca", "azeite", "sal"],
      steps: ["Aquece azeite.", "Milho até abrir.", "Sal."],
      note: "Baseado em técnicas clássicas · ref. stovetop popcorn: https://www.allrecipes.com/recipe/11887/homemade-popcorn/",
    },
    {
      section: "lanches",
      title: "Queijo halloumi grelhado",
      subtitle: "10 min",
      protein_note: "~18 g",
      tags: ["quente"],
      ingredients: ["halloumi", "limão"],
      steps: ["Grelha fatias 2 min/lado.", "Limão."],
      note: "Baseado em técnicas clássicas · ref. halloumi snack: https://www.bbcgoodfood.com/recipes/collection/halloumi-recipes",
    },
    {
      section: "lanches",
      title: "Ricotta com mel e nozes",
      subtitle: "Colher",
      protein_note: "~14 g",
      tags: ["soft"],
      ingredients: ["ricotta", "mel", "nozes"],
      steps: ["Mistura na taça."],
      note: "Baseado em técnicas clássicas · ref. ricotta honey: https://www.bbcgoodfood.com/recipes/ricotta-toast",
    },
    {
      section: "lanches",
      title: "Tostas de batata-doce",
      subtitle: "Forno",
      protein_note: "~6 g",
      tags: ["forno"],
      ingredients: ["batata-doce em rodelas", "azeite", "sal"],
      steps: ["Unta e asa 200 °C até macias/douradas."],
      note: "Baseado em técnicas clássicas · ref. sweet potato rounds: https://www.bbcgoodfood.com/recipes/collection/sweet-potato-recipes",
    },
    {
      section: "lanches",
      title: "Shake de leite e café",
      subtitle: "Frappe simples",
      protein_note: "~10 g",
      tags: ["líquido"],
      ingredients: ["leite", "café frio", "gelo", "mel"],
      steps: ["Tritura."],
      note: "Baseado em técnicas clássicas · ref. iced coffee milk: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "lanches",
      title: "Palitos de queijo e fiambre",
      subtitle: "Enrolados",
      protein_note: "~16 g",
      tags: ["rápido"],
      ingredients: ["queijo em palitos", "fiambre"],
      steps: ["Enrola fiambre no queijo."],
      note: "Baseado em técnicas clássicas · ref. meat cheese sticks: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Guacamole com tortilha chips",
      subtitle: "Dip",
      protein_note: "~8 g",
      tags: ["share"],
      ingredients: ["abacate", "limão", "sal", "tomate", "chips"],
      steps: ["Esmaga abacate.", "Tempera.", "Serve com chips."],
      note: "Baseado em técnicas clássicas · ref. guacamole: https://www.bbcgoodfood.com/recipes/guacamole",
    },
    {
      section: "lanches",
      title: "Massa de atum à colher",
      subtitle: "Soft",
      protein_note: "~20 g",
      tags: ["soft"],
      ingredients: ["atum", "maionese", "pão mole"],
      steps: ["Mistura patê.", "Come à colher ou com pão."],
      note: "Baseado em técnicas clássicas · ref. tuna snack: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "lanches",
      title: "Gelatina proteica / iogurte gelado",
      subtitle: "Frio",
      protein_note: "~15 g",
      tags: ["doce"],
      ingredients: ["iogurte grego", "gelatina sem sabor opcional", "fruta"],
      steps: ["Mistura e arrefece até firmar."],
      note: "Baseado em técnicas clássicas · ref. yogurt jelly: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Tosta de abacate snack",
      subtitle: "Meia dose",
      protein_note: "~10 g",
      tags: ["rápido"],
      ingredients: ["1 fatia pão", "1/2 abacate", "sal", "pimenta"],
      steps: ["Esmaga e espalma."],
      note: "Baseado em técnicas clássicas · ref. avocado snack: https://www.bbcgoodfood.com/recipes/smashed-avocado-on-toast",
    },
    {
      section: "lanches",
      title: "Cenouras baby e guacamole",
      subtitle: "Dip",
      protein_note: "~6 g",
      tags: ["leve"],
      ingredients: ["cenouras", "guacamole"],
      steps: ["Mergulha."],
      note: "Baseado em técnicas clássicas · ref. veggie dip: https://www.bbcgoodfood.com/recipes/guacamole",
    },
    {
      section: "lanches",
      title: "Cookie de micro-ondas (mug)",
      subtitle: "2 min",
      protein_note: "~6 g",
      tags: ["doce"],
      ingredients: ["aveia", "ovo ou banana", "cacau", "mel"],
      steps: ["Mistura na caneca.", "Micro-ondas 60–90 s."],
      note: "Baseado em técnicas clássicas · ref. mug cookie: https://www.bbcgoodfood.com/recipes/collection/mug-cake-recipes",
    },
    {
      section: "lanches",
      title: "Queijo fresco com orégãos e azeite",
      subtitle: "Mediterrânico",
      protein_note: "~12 g",
      tags: ["soft"],
      ingredients: ["queijo fresco", "azeite", "orégãos", "pão"],
      steps: ["Tempera e come com pão."],
      note: "Baseado em técnicas clássicas · ref. greek snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Smoothie verde suave",
      subtitle: "Banana+espinafre",
      protein_note: "~12 g",
      tags: ["líquido"],
      ingredients: ["banana", "espinafre bebé", "leite", "mel"],
      steps: ["Tritura bem."],
      note: "Baseado em técnicas clássicas · ref. green smoothie: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "lanches",
      title: "Nachos rápidos de micro-ondas",
      subtitle: "5 min",
      protein_note: "~14 g",
      tags: ["quente"],
      ingredients: ["tortilha chips", "queijo ralado", "feijão ou frango"],
      steps: ["Chips + queijo + proteína.", "Micro-ondas até derreter."],
      note: "Baseado em técnicas clássicas · ref. microwave nachos: https://www.allrecipes.com/recipe/27078/microwave-nachos/",
    },
    {
      section: "lanches",
      title: "Fatias de peru enroladas em queijo",
      subtitle: "0 fogão",
      protein_note: "~18 g",
      tags: ["leva-te"],
      ingredients: ["peru", "queijo creme ou fatia"],
      steps: ["Espalma queijo no peru.", "Enrolha."],
      note: "Baseado em técnicas clássicas · ref. deli roll-ups: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Azeitonas e tomate cherry",
      subtitle: "Mediterrânico",
      protein_note: "~2 g",
      tags: ["leve"],
      ingredients: ["azeitonas", "tomate cherry"],
      steps: ["Tigela mista."],
      note: "Baseado em técnicas clássicas · ref. antipasti snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Pão com azeite e sal",
      subtitle: "Minimal",
      protein_note: "~4 g",
      tags: ["simples"],
      ingredients: ["pão bom", "azeite", "flor de sal"],
      steps: ["Molha ou rega o pão."],
      note: "Baseado em técnicas clássicas · ref. pa amb oli snack: https://www.bbcgoodfood.com/recipes/pan-con-tomate",
    },
    {
      section: "lanches",
      title: "Iogurte com granola snack",
      subtitle: "Meia taça",
      protein_note: "~12 g",
      tags: ["soft"],
      ingredients: ["iogurte", "granola"],
      steps: ["Monta na taça."],
      note: "Baseado em técnicas clássicas · ref. yogurt granola: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes",
    },
    {
      section: "lanches",
      title: "Batata cozida com sal",
      subtitle: "Soft",
      protein_note: "~4 g",
      tags: ["soft"],
      ingredients: ["batata pequenina", "sal", "azeite"],
      steps: ["Coze.", "Azeite e sal."],
      note: "Baseado em técnicas clássicas · ref. boiled potatoes snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Trutas de atum em alface",
      subtitle: "Low carb",
      protein_note: "~18 g",
      tags: ["leve"],
      ingredients: ["atum", "maionese", "folhas alface"],
      steps: ["Patê de atum em folhas."],
      note: "Baseado em técnicas clássicas · ref. tuna lettuce cups: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Chocolate quente proteico",
      subtitle: "Leite + cacau",
      protein_note: "~12 g",
      tags: ["quente"],
      ingredients: ["leite", "cacau", "mel", "pitada sal"],
      steps: ["Aquece mexendo."],
      note: "Baseado em técnicas clássicas · ref. hot cocoa: https://www.bbcgoodfood.com/recipes/collection/hot-chocolate-recipes",
    },
    {
      section: "lanches",
      title: "Sementes de abóbora tostadas",
      subtitle: "Crocante",
      protein_note: "~8 g",
      tags: ["leva-te"],
      ingredients: ["sementes abóbora", "azeite", "sal"],
      steps: ["Tosta 8–10 min 180 °C."],
      note: "Baseado em técnicas clássicas · ref. roasted pumpkin seeds: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Pêra com queijo azul",
      subtitle: "Gourmet",
      protein_note: "~10 g",
      tags: ["simples"],
      ingredients: ["pêra", "queijo azul ou curado"],
      steps: ["Fatias alternadas."],
      note: "Baseado em técnicas clássicas · ref. fruit cheese: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Muffin de ovo reaquecido",
      subtitle: "Meal prep",
      protein_note: "~12 g",
      tags: ["quente"],
      ingredients: ["egg muffin já feito"],
      steps: ["Reaquece 30–40 s no micro-ondas."],
      note: "Baseado em técnicas clássicas · ref. NYT egg muffins: https://cooking.nytimes.com/recipes/1026058-egg-muffins",
    },
    {
      section: "lanches",
      title: "Tapioca snack com coco",
      subtitle: "Doce",
      protein_note: "~6 g",
      tags: ["frigideira"],
      ingredients: ["tapioca", "coco ralado", "leite condensado leve opcional"],
      steps: ["Tapioca na frigideira.", "Coco; dobra."],
      note: "Baseado em técnicas clássicas · ref. tapioca doce: https://www.tudogostoso.com.br/receita/29876-tapioca.htm",
    },
    {
      section: "lanches",
      title: "Gazpacho em copo",
      subtitle: "Frio",
      protein_note: "~4 g",
      tags: ["líquido"],
      ingredients: ["gazpacho pronto ou caseiro"],
      steps: ["Serve bem frio em copo."],
      note: "Baseado em técnicas clássicas · ref. gazpacho: https://www.bbcgoodfood.com/recipes/gazpacho",
    },
    {
      section: "lanches",
      title: "Bolachas de arroz com atum",
      subtitle: "Rápido",
      protein_note: "~14 g",
      tags: ["rápido"],
      ingredients: ["bolacha arroz", "atum", "ricotta ou cream cheese"],
      steps: ["Base de queijo.", "Atum por cima."],
      note: "Baseado em técnicas clássicas · ref. rice cake snack: https://www.bbcgoodfood.com/recipes/collection/snack-recipes",
    },
    {
      section: "lanches",
      title: "Milkshake de morango simples",
      subtitle: "3 min",
      protein_note: "~10 g",
      tags: ["líquido"],
      ingredients: ["morangos", "leite", "gelado ou iogurte", "mel"],
      steps: ["Tritura."],
      note: "Baseado em técnicas clássicas · ref. strawberry milkshake: https://www.bbcgoodfood.com/recipes/collection/smoothie-recipes",
    },
    {
      section: "jantar",
      title: "Hambúrgueres caseiros",
      subtitle: "Carne e queijo",
      protein_note: "~40 g",
      tags: ["estrela"],
      ingredients: ["400 g carne picada", "pães", "queijo", "alface", "tomate", "sal"],
      steps: ["Forma 2 discos.", "Grelha 3–4 min/lado.", "Queijo no fim.", "Monta."],
      note: "Baseado em técnicas clássicas · ref. clássico burger: https://www.seriouseats.com/smash-burgers-recipe",
    },
    {
      section: "jantar",
      title: "Esparguete à bolonhesa",
      subtitle: "30–40 min",
      protein_note: "~35 g",
      tags: ["clássico"],
      ingredients: ["massa", "carne picada", "cebola", "alho", "tomate", "queijo"],
      steps: ["Refoga aromáticos.", "Coze carne.", "Tomate 15 min.", "Mistura massa."],
      note: "Baseado em técnicas clássicas · ref. ragu rápido: https://www.bbcgoodfood.com/recipes/best-spaghetti-bolognese-recipe",
    },
    {
      section: "jantar",
      title: "Bifanas no pão",
      subtitle: "À portuguesa",
      protein_note: "~38 g",
      tags: ["tacho"],
      ingredients: ["bifanas", "alho", "louro", "vinho branco", "pão"],
      steps: ["Doura bifanas com alho.", "Vinho e reduz.", "Pão com molho."],
      note: "Baseado em técnicas clássicas · ref. Pingo Doce bifanas: https://www.pingodoce.pt/receitas/bifanas-a-moda-do-porto/",
    },
    {
      section: "jantar",
      title: "Frango panado na frigideira",
      subtitle: "25 min",
      protein_note: "~40 g",
      tags: ["frigideira"],
      ingredients: ["peitos frango", "ovo", "pão ralado", "óleo", "limão"],
      steps: ["Passa no ovo e pão ralado.", "Frita até dourar.", "Limão."],
      note: "Baseado em técnicas clássicas · ref. escalope clássico: https://www.bbcgoodfood.com/recipes/chicken-schnitzel",
    },
    {
      section: "jantar",
      title: "Cajun chicken pasta",
      subtitle: "30 min · cremosa",
      protein_note: "~38 g",
      tags: ["massa"],
      ingredients: ["frango", "massa", "pimentões", "natas", "tempero cajun"],
      steps: ["Tempra e salteia frango.", "Refoga pimentões.", "Natas + tempero.", "Mistura massa."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes Cajun Chicken Pasta: https://www.allrecipes.com/recipe/8778/cajun-chicken-pasta/",
    },
    {
      section: "jantar",
      title: "Chicken Alfredo",
      subtitle: "Fettuccine cremoso",
      protein_note: "~36 g",
      tags: ["massa"],
      ingredients: ["frango", "fettuccine", "natas", "parmesão", "manteiga", "alho"],
      steps: ["Coze massa.", "Salteia frango.", "Molho manteiga+natas+parmesão.", "Junta tudo."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes Chicken Alfredo: https://www.allrecipes.com/recipe/25303/chicken-fettuccini-alfredo/",
    },
    {
      section: "jantar",
      title: "Penne frango e pesto",
      subtitle: "30 min",
      protein_note: "~34 g",
      tags: ["massa"],
      ingredients: ["penne", "frango", "pesto", "natas ou azeite", "parmesão"],
      steps: ["Coze massa.", "Salteia frango.", "Envolve pesto e queijo."],
      note: "Baseado em técnicas clássicas · ref. Allrecipes penne pesto chicken: https://www.allrecipes.com/recipe/26284/penne-with-chicken-and-pesto/",
    },
    {
      section: "jantar",
      title: "Bife com ovo a cavalo",
      subtitle: "Clássico tasca",
      protein_note: "~40 g",
      tags: ["frigideira"],
      ingredients: ["bife", "ovos", "alho", "manteiga", "batata ou pão"],
      steps: ["Frita bife.", "Ovos estrelados em cima.", "Acompanhar."],
      note: "Baseado em técnicas clássicas · ref. clássico PT: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "jantar",
      title: "Esparguete atum e alho",
      subtitle: "15 min",
      protein_note: "~30 g",
      tags: ["lata"],
      ingredients: ["esparguete", "atum", "alho", "azeite", "malagueta"],
      steps: ["Coze massa.", "Alho no azeite.", "Junta atum e massa."],
      note: "Baseado em técnicas clássicas · ref. classic pantry pasta: https://www.bbcgoodfood.com/recipes/tuna-pasta",
    },
    {
      section: "jantar",
      title: "Tacos de carne picada",
      subtitle: "25 min",
      protein_note: "~35 g",
      tags: ["fun"],
      ingredients: ["carne picada", "tortilhas", "cebola", "cominhos", "alface", "queijo"],
      steps: ["Refoga carne com temperos.", "Aquece tortilhas.", "Recheia."],
      note: "Baseado em técnicas clássicas · ref. beef tacos: https://www.bbcgoodfood.com/recipes/beef-tacos",
    },
    {
      section: "jantar",
      title: "Frango à Brás",
      subtitle: "PT conforto",
      protein_note: "~32 g",
      tags: ["tacho"],
      ingredients: ["frango desfiado", "batata palha", "ovos", "cebola", "azeite"],
      steps: ["Refoga cebola.", "Junta frango.", "Ovos mexidos.", "Batata palha no fim."],
      note: "Baseado em técnicas clássicas · ref. adaptação Brás: https://www.teleculinaria.pt/",
    },
    {
      section: "jantar",
      title: "Francesinha simplificada",
      subtitle: "Molho cerveja",
      protein_note: "~45 g",
      tags: ["porto"],
      ingredients: ["pão de forma", "bife", "fiambre", "salsicha", "queijo", "cerveja", "tomate"],
      steps: ["Grelha carnes.", "Monta sandes e cobre queijo.", "Ferve molho tomate-cerveja.", "Banha e gratinar."],
      note: "Baseado em técnicas clássicas · ref. Teleculinária / Pingo Doce: https://www.pingodoce.pt/receitas/francesinha/",
    },
    {
      section: "jantar",
      title: "Salmão grelhado com limão",
      subtitle: "20 min",
      protein_note: "~34 g",
      tags: ["peixe"],
      ingredients: ["salmão", "azeite", "limão", "sal", "pimenta"],
      steps: ["Tempra.", "Grelha 3–4 min/lado.", "Limão."],
      note: "Baseado em técnicas clássicas · ref. BBC grilled salmon: https://www.bbcgoodfood.com/recipes/collection/salmon-recipes",
    },
    {
      section: "jantar",
      title: "Risotto de cogumelos",
      subtitle: "35 min",
      protein_note: "~12 g",
      tags: ["1 panela"],
      ingredients: ["arroz arbóreo", "cogumelos", "cebola", "caldo", "parmesão", "manteiga"],
      steps: ["Refoga cebola e cogumelos.", "Tosta arroz.", "Caldo aos poucos.", "Manteiga e parmesão."],
      note: "Baseado em técnicas clássicas · ref. BBC mushroom risotto: https://www.bbcgoodfood.com/recipes/mushroom-risotto",
    },
    {
      section: "jantar",
      title: "Frango assado no forno",
      subtitle: "60–75 min",
      protein_note: "~40 g",
      tags: ["forno"],
      ingredients: ["frango inteiro ou coxas", "alho", "limão", "azeite", "batatas"],
      steps: ["Tempra bem.", "Assa 200 °C até cozido.", "Descanse 10 min."],
      note: "Baseado em técnicas clássicas · ref. BBC roast chicken: https://www.bbcgoodfood.com/recipes/perfect-roast-chicken",
    },
    {
      section: "jantar",
      title: "Chili con carne",
      subtitle: "40 min",
      protein_note: "~32 g",
      tags: ["tacho"],
      ingredients: ["carne picada", "feijão", "tomate", "cominhos", "chili", "arroz"],
      steps: ["Refoga carne.", "Especiarias e tomate.", "Feijão 20 min.", "Arroz."],
      note: "Baseado em técnicas clássicas · ref. BBC chilli con carne: https://www.bbcgoodfood.com/recipes/chilli-con-carne-recipe",
    },
    {
      section: "jantar",
      title: "Pizza na frigideira",
      subtitle: "Wrap pizza · 15 min",
      protein_note: "~28 g",
      tags: ["frigideira"],
      ingredients: ["wrap", "passata", "queijo", "fiambre"],
      steps: ["Wrap na frigideira.", "Tomate, queijo, toppings.", "Tapa até derreter."],
      note: "Baseado em técnicas clássicas · ref. skillet pizza: https://www.bbcgoodfood.com/recipes/collection/pizza-recipes",
    },
    {
      section: "jantar",
      title: "Strogonoff de frango",
      subtitle: "30 min",
      protein_note: "~35 g",
      tags: ["tacho"],
      ingredients: ["frango", "natas", "mostarda", "ketchup ou molho inglês", "arroz", "batata palha"],
      steps: ["Salteia frango.", "Mostarda e ketchup.", "Natas.", "Arroz e batata palha."],
      note: "Baseado em técnicas clássicas · ref. strogonoff BR/PT: https://www.tudogostoso.com.br/receita/2525-estrogonofe-de-frango.htm",
    },
    {
      section: "jantar",
      title: "Lasanha clássica",
      subtitle: "Forno · 60 min",
      protein_note: "~30 g",
      tags: ["forno"],
      ingredients: ["folhas lasanha", "boloese", "bechamel", "queijo"],
      steps: ["Camadas molho/massa/queijo.", "180 °C 35–45 min."],
      note: "Baseado em técnicas clássicas · ref. BBC lasagne: https://www.bbcgoodfood.com/recipes/classic-lasagne",
    },
    {
      section: "jantar",
      title: "Peixe no forno com batata",
      subtitle: "40 min",
      protein_note: "~32 g",
      tags: ["forno"],
      ingredients: ["filetes peixe", "batata", "azeite", "alho", "limão"],
      steps: ["Batata primeiro 20 min.", "Peixe por cima mais 15 min."],
      note: "Baseado em técnicas clássicas · ref. traybake peixe: https://www.bbcgoodfood.com/recipes/collection/traybake-recipes",
    },
    {
      section: "jantar",
      title: "Caril de frango simples",
      subtitle: "35 min",
      protein_note: "~34 g",
      tags: ["tacho"],
      ingredients: ["frango", "curry em pó", "cebola", "leite coco ou natas", "arroz"],
      steps: ["Refoga cebola.", "Frango + curry.", "Líquido 15 min.", "Arroz."],
      note: "Baseado em técnicas clássicas · ref. BBC chicken curry: https://www.bbcgoodfood.com/recipes/easy-chicken-curry",
    },
    {
      section: "jantar",
      title: "Quesadillas de frango",
      subtitle: "15 min",
      protein_note: "~32 g",
      tags: ["rápido"],
      ingredients: ["tortilhas", "frango", "queijo"],
      steps: ["Recheia e doura.", "Corta."],
      note: "Baseado em técnicas clássicas · ref. quesadilla: https://www.bbcgoodfood.com/recipes/collection/quesadilla-recipes",
    },
    {
      section: "jantar",
      title: "Costeletas de porco grelhadas",
      subtitle: "20 min",
      protein_note: "~36 g",
      tags: ["grelha"],
      ingredients: ["costeletas", "alho", "azeite", "sal", "pimenta"],
      steps: ["Tempra.", "Grelha 4–5 min/lado.", "Descansa."],
      note: "Baseado em técnicas clássicas · ref. pork chops: https://www.bbcgoodfood.com/recipes/collection/pork-chop-recipes",
    },
    {
      section: "jantar",
      title: "Massa carbonara sem nata",
      subtitle: "25 min",
      protein_note: "~28 g",
      tags: ["clássico"],
      ingredients: ["esparguete", "ovos", "guanciale ou bacon", "pecorino/parmesão"],
      steps: ["Coze massa.", "Doura bacon.", "Mistura ovos+queijo fora do lume com massa quente."],
      note: "Baseado em técnicas clássicas · ref. Serious Eats carbonara: https://www.seriouseats.com/spaghetti-alla-carbonara-recipe",
    },
    {
      section: "jantar",
      title: "Fajitas de frango",
      subtitle: "25 min",
      protein_note: "~34 g",
      tags: ["fun"],
      ingredients: ["frango tiras", "pimentões", "cebola", "especiarias", "tortilhas"],
      steps: ["Salteia frango e vegetais.", "Serve em tortilhas."],
      note: "Baseado em técnicas clássicas · ref. BBC chicken fajitas: https://www.bbcgoodfood.com/recipes/chicken-fajitas",
    },
    {
      section: "jantar",
      title: "Bacalhau à Brás",
      subtitle: "30 min",
      protein_note: "~30 g",
      tags: ["PT"],
      ingredients: ["bacalhau desfiado", "batata palha", "ovos", "cebola"],
      steps: ["Refoga cebola.", "Bacalhau.", "Ovos.", "Batata palha."],
      note: "Baseado em técnicas clássicas · ref. Teleculinária bacalhau Brás: https://teleculinaria.pt/",
    },
    {
      section: "jantar",
      title: "Bacalhau Gomes de Sá",
      subtitle: "Forno",
      protein_note: "~32 g",
      tags: ["PT"],
      ingredients: ["bacalhau", "batata", "cebola", "ovos", "azeitonas", "azeite"],
      steps: ["Coze bacalhau e batata.", "Refoga cebola.", "Mistura e leva ao forno.", "Ovos e azeitonas."],
      note: "Baseado em técnicas clássicas · ref. Gomes de Sá: https://arcadasportofado.pt/receitas/bacalhau-a-gomes-de-sa-2/",
    },
    {
      section: "jantar",
      title: "Sopa de legumes com grão",
      subtitle: "leve jantar",
      protein_note: "~14 g",
      tags: ["sopa"],
      ingredients: ["legumes", "grão", "caldo", "azeite"],
      steps: ["Refoga.", "Coze legumes.", "Junta grão.", "Tritura parcial se quiseres."],
      note: "Baseado em técnicas clássicas · ref. vegetable soup: https://www.bbcgoodfood.com/recipes/collection/soup-recipes",
    },
    {
      section: "jantar",
      title: "Frango teriyaki rápido",
      subtitle: "20 min",
      protein_note: "~34 g",
      tags: ["frigideira"],
      ingredients: ["frango", "molho soja", "mel", "alho", "arroz", "sementes sésamo"],
      steps: ["Salteia frango.", "Soja+mel+alho até engrossar.", "Arroz."],
      note: "Baseado em técnicas clássicas · ref. teriyaki chicken: https://www.bbcgoodfood.com/recipes/teriyaki-chicken",
    },
    {
      section: "jantar",
      title: "Omelete carregada de jantar",
      subtitle: "10 min",
      protein_note: "~35 g",
      tags: ["preguiçoso"],
      ingredients: ["4 ovos", "fiambre", "queijo", "pão"],
      steps: ["Omelete com recheio.", "Pão a acompanhar."],
      note: "Baseado em técnicas clássicas · ref. dinner omelette: https://www.seriouseats.com/the-best-french-omelette-recipe",
    },
    {
      section: "jantar",
      title: "Espetadas de frango",
      subtitle: "Grelha · 25 min",
      protein_note: "~34 g",
      tags: ["grelha"],
      ingredients: ["frango em cubos", "pimentão", "cebola", "azeite", "especiarias"],
      steps: ["Espeta.", "Grelha virando.", "Serve com arroz ou pão."],
      note: "Baseado em técnicas clássicas · ref. chicken skewers: https://www.bbcgoodfood.com/recipes/collection/skewer-recipes",
    },
    {
      section: "jantar",
      title: "Massa com camarão ao alho",
      subtitle: "20 min",
      protein_note: "~30 g",
      tags: ["marisco"],
      ingredients: ["massa", "camarão", "alho", "azeite", "malagueta", "salsa"],
      steps: ["Coze massa.", "Salteia camarão com alho.", "Envolve."],
      note: "Baseado em técnicas clássicas · ref. garlic prawn pasta: https://www.bbcgoodfood.com/recipes/garlic-prawn-pasta",
    },
    {
      section: "jantar",
      title: "Shepherd's pie rápido",
      subtitle: "45 min",
      protein_note: "~28 g",
      tags: ["forno"],
      ingredients: ["carne picada", "ervilhas/cenoura", "puré batata", "queijo"],
      steps: ["Refoga carne com vegetais.", "Cobre com puré.", "Gratinar."],
      note: "Baseado em técnicas clássicas · ref. BBC shepherd's pie: https://www.bbcgoodfood.com/recipes/shepherds-pie",
    },
    {
      section: "jantar",
      title: "Frango xadrez simples",
      subtitle: "30 min",
      protein_note: "~32 g",
      tags: ["wok"],
      ingredients: ["frango", "pimentões", "amendoim", "molho soja", "amido"],
      steps: ["Salteia frango.", "Vegetais.", "Molho até engrossar."],
      note: "Baseado em técnicas clássicas · ref. kung pao style: https://www.bbcgoodfood.com/recipes/collection/stir-fry-recipes",
    },
    {
      section: "jantar",
      title: "Arroz de pato ou frango",
      subtitle: "Uma panela",
      protein_note: "~30 g",
      tags: ["1 panela"],
      ingredients: ["arroz", "frango", "chouriço opcional", "caldo", "cebola"],
      steps: ["Refoga.", "Arroz + caldo.", "Coze até secar."],
      note: "Baseado em técnicas clássicas · ref. arroz de frango PT: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "jantar",
      title: "Moussaka rápida",
      subtitle: "50 min",
      protein_note: "~28 g",
      tags: ["forno"],
      ingredients: ["beringela", "carne picada", "tomate", "bechamel ou iogurte+ovo"],
      steps: ["Grelha beringela.", "Camadas com carne.", "Cobertura.", "Forno."],
      note: "Baseado em técnicas clássicas · ref. moussaka: https://www.bbcgoodfood.com/recipes/moussaka",
    },
    {
      section: "jantar",
      title: "Salsichas com puré",
      subtitle: "Comfort",
      protein_note: "~25 g",
      tags: ["rápido"],
      ingredients: ["salsichas", "batata", "manteiga", "leite"],
      steps: ["Grelha salsichas.", "Puré cremoso."],
      note: "Baseado em técnicas clássicas · ref. bangers and mash: https://www.bbcgoodfood.com/recipes/bangers-mash",
    },
    {
      section: "jantar",
      title: "Peito de frango grelhado com salada",
      subtitle: "20 min",
      protein_note: "~40 g",
      tags: ["leve"],
      ingredients: ["peito frango", "azeite", "salada", "limão"],
      steps: ["Grelha frango.", "Fatia sobre salada."],
      note: "Baseado em técnicas clássicas · ref. grilled chicken salad: https://www.bbcgoodfood.com/recipes/collection/chicken-salad-recipes",
    },
    {
      section: "jantar",
      title: "Pad Thai rápido",
      subtitle: "25 min",
      protein_note: "~28 g",
      tags: ["wok"],
      ingredients: ["noodles arroz", "ovo", "camarão ou frango", "molho peixe/soja", "amendoim"],
      steps: ["Amaia noodles.", "Salteia proteína e ovo.", "Molho e amendoim."],
      note: "Baseado em técnicas clássicas · ref. pad thai: https://www.bbcgoodfood.com/recipes/pad-thai",
    },
    {
      section: "jantar",
      title: "Empadão de carne",
      subtitle: "Forno",
      protein_note: "~30 g",
      tags: ["forno"],
      ingredients: ["carne picada", "puré", "cebola", "ervilha"],
      steps: ["Refoga carne.", "Cobre puré.", "Gratinar."],
      note: "Baseado em técnicas clássicas · ref. cottage pie: https://www.bbcgoodfood.com/recipes/cottage-pie",
    },
    {
      section: "jantar",
      title: "Lulas grelhadas com alho",
      subtitle: "15 min",
      protein_note: "~28 g",
      tags: ["grelha"],
      ingredients: ["lulas", "alho", "azeite", "salsa", "limão"],
      steps: ["Tempra.", "Grelha rápido.", "Alho e salsa."],
      note: "Baseado em técnicas clássicas · ref. grilled squid: https://www.bbcgoodfood.com/recipes/collection/squid-recipes",
    },
    {
      section: "jantar",
      title: "Feijoada rápida de frango",
      subtitle: "40 min",
      protein_note: "~30 g",
      tags: ["tacho"],
      ingredients: ["feijão", "frango", "chouriço", "cebola", "arroz"],
      steps: ["Refoga.", "Estufa com feijão.", "Arroz."],
      note: "Baseado em técnicas clássicas · ref. feijoada light: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "jantar",
      title: "Massa puttanesca",
      subtitle: "20 min",
      protein_note: "~14 g",
      tags: ["despensa"],
      ingredients: ["massa", "tomate", "azeitonas", "alcaparras", "alho", "anchova opcional"],
      steps: ["Molho rápido de tomate e salgados.", "Envolve massa."],
      note: "Baseado em técnicas clássicas · ref. puttanesca: https://www.seriouseats.com/pasta-puttanesca-recipe",
    },
    {
      section: "jantar",
      title: "Costela ou entrecosto no forno",
      subtitle: "Lento",
      protein_note: "~35 g",
      tags: ["forno"],
      ingredients: ["entrecosto", "alho", "mostarda", "mel ou melado", "sal"],
      steps: ["Tempra.", "Assa coberto depois descoberto até caramelizar."],
      note: "Baseado em técnicas clássicas · ref. BBQ ribs style: https://www.bbcgoodfood.com/recipes/collection/ribs-recipes",
    },
    {
      section: "jantar",
      title: "Tofu salteado com legumes",
      subtitle: "25 min",
      protein_note: "~22 g",
      tags: ["vegetariano"],
      ingredients: ["tofu firme", "legumes", "soja", "alho", "arroz"],
      steps: ["Seca e doura tofu.", "Salteia legumes.", "Molho soja."],
      note: "Baseado em técnicas clássicas · ref. tofu stir-fry: https://www.bbcgoodfood.com/recipes/collection/tofu-recipes",
    },
    {
      section: "jantar",
      title: "Caldo verde com chouriço",
      subtitle: "35 min",
      protein_note: "~18 g",
      tags: ["PT", "sopa"],
      ingredients: ["batata", "couve galega", "chouriço", "azeite"],
      steps: ["Coze batata e tritura.", "Junta couve fina.", "Chouriço a acompanhar."],
      note: "Baseado em técnicas clássicas · ref. caldo verde: https://www.pingodoce.pt/receitas/",
    },
    {
      section: "jantar",
      title: "Frango cacciatore rápido",
      subtitle: "35 min",
      protein_note: "~34 g",
      tags: ["tacho"],
      ingredients: ["frango", "tomate", "pimento", "azeitonas", "alho"],
      steps: ["Doura frango.", "Molho tomate e vegetais.", "Estufa até tenro."],
      note: "Baseado em técnicas clássicas · ref. chicken cacciatore: https://www.bbcgoodfood.com/recipes/chicken-cacciatore",
    },
    {
      section: "jantar",
      title: "Noodles de carne picada asiáticos",
      subtitle: "20 min",
      protein_note: "~30 g",
      tags: ["rápido"],
      ingredients: ["noodles", "carne picada", "soja", "alho", "cebolinho"],
      steps: ["Salteia carne.", "Noodles e molho.", "Cebolinho."],
      note: "Baseado em técnicas clássicas · ref. Asian beef noodles: https://www.bbcgoodfood.com/recipes/collection/noodle-recipes",
    },
    {
      section: "jantar",
      title: "Polvo à lagareiro (versão fácil)",
      subtitle: "Forno",
      protein_note: "~32 g",
      tags: ["PT"],
      ingredients: ["polvo pré-cozido", "batata", "alho", "azeite", "salsa"],
      steps: ["Batatas ao murro.", "Polvo por cima com alho e azeite.", "Forno quente."],
      note: "Baseado em técnicas clássicas · ref. polvo lagareiro: https://www.teleculinaria.pt/",
    },
    {
      section: "jantar",
      title: "Ratatouille com ovo ou queijo",
      subtitle: "35 min",
      protein_note: "~14 g",
      tags: ["vegetariano"],
      ingredients: ["beringela", "courgette", "pimento", "tomate", "azeite"],
      steps: ["Refoga vegetais em camadas ou tudo junto.", "Coze até macios.", "Ovo ou queijo por cima."],
      note: "Baseado em técnicas clássicas · ref. ratatouille: https://www.bbcgoodfood.com/recipes/ratatouille",
    },
  ],

  shoppingLists: [
  {
    "name": "Supermercado",
    "items": [
      "Ovos",
      "Atum em lata",
      "Peito de frango",
      "Carne picada",
      "Bifanas",
      "Fiambre / peru",
      "Salmão fumado",
      "Iogurte grego",
      "Queijo",
      "Cream cheese",
      "Pasta de amendoim",
      "Pão mole",
      "Wraps",
      "Massa",
      "Maionese",
      "Tomate pelado",
      "Leite",
      "Aveia",
      "Mel e granola",
      "Alface e tomate",
      "Alho e cebola",
      "Bananas",
      "Limões",
      "Batatas",
      "Azeite e manteiga",
      "Sal, pimenta, orégãos"
    ]
  },
  {
    "name": "Praia / mala térmica",
    "items": [
      "Gelo / acumuladores",
      "Mala térmica",
      "Água",
      "Wraps ou pão",
      "Sandes já feitas",
      "Ovos cozidos",
      "Fruta mole",
      "Guardanapos"
    ]
  }
]
};
