/* Dados iniciais — inseridos na primeira vez que entras na conta.
   Receitas clássicas com passos de cozedura detalhados (técnicas habituais). */
window.MARE_SEED = {
  recipes: [
    // —— Manhã ——
    {
      section: "manha",
      title: "Ovos mexidos cremosos",
      subtitle: "Lume baixo · 8–10 min",
      protein_note: "~20–25 g proteína",
      tags: ["clássico", "1 panela"],
      ingredients: [
        "3 ovos grandes",
        "1 colher de sopa de manteiga",
        "1 pitada de sal fino",
        "Pimenta preta a gosto",
        "Opcional: 2 fatias de fiambre ou peito de peru picado",
        "Opcional: 2 colheres de sopa de queijo ralado",
        "Pão tostado para servir",
      ],
      steps: [
        "Parte os ovos para uma taça. Bate só até as gemas e claras se misturarem — não é preciso espuma.",
        "Mete a manteiga numa frigideira antiaderente em lume baixo. Quando derreter e espumar de leve, deita os ovos.",
        "Com uma espátula de borracha, empurra os ovos das bordas para o centro. Mexe devagar, sem parar, para cozerem em coalhada fina.",
        "Quando ainda estiverem ligeiramente húmidos (não secos), tira a frigideira do lume — o calor residual acaba a cozedura.",
        "Se usares fiambre e queijo, junta agora, fora do lume, e envolve. Tempera com sal e pimenta.",
        "Serve de imediato com pão tostado.",
      ],
      note: "O segredo dos ovos mexidos cremosos é lume baixo e tirar do fogão um pouco antes de parecerem prontos.",
    },
    {
      section: "manha",
      title: "Iogurte grego com mel e granola",
      subtitle: "Sem fogão · 2 min",
      protein_note: "~18–22 g proteína",
      tags: ["sem fogão", "rápido"],
      ingredients: [
        "200–250 g de iogurte grego natural",
        "1–2 colheres de chá de mel",
        "3–4 colheres de sopa de granola",
        "Opcional: ½ banana em rodelas",
        "Opcional: 1 colher de sopa de pasta de amendoim",
      ],
      steps: [
        "Deita o iogurte numa taça e alisa a superfície com o dorso da colher.",
        "Rega com o mel em fio.",
        "Se quiseres mais proteína e cremosidade, envolve a pasta de amendoim no iogurte antes da granola.",
        "Espalha a granola por cima (assim não amolece toda de uma vez).",
        "Acrescenta a banana, se usares, e come de imediato.",
      ],
    },
    {
      section: "manha",
      title: "Tosta de ovo estrelado e queijo",
      subtitle: "Tipo brunch · 10 min",
      protein_note: "~22 g proteína",
      tags: ["frigideira"],
      ingredients: [
        "2 fatias de pão de forma ou pão rústico",
        "2 ovos",
        "2 fatias de queijo (flamengo, cheddar ou similar)",
        "Manteiga ou azeite para fritar",
        "Sal e pimenta",
        "Opcional: 1–2 fatias de fiambre",
      ],
      steps: [
        "Aquece uma frigideira em lume médio-baixo com um pouco de manteiga.",
        "Tosta as fatias de pão dos dois lados até ficarem douradas. Reserva.",
        "Na mesma frigideira, deita mais um pouco de manteiga. Parte os ovos com cuidado para a gema não partir.",
        "Tempra com sal e pimenta. Coze 2–3 minutos: clara presa e gema ainda mole (ou mais tempo se preferires gema dura).",
        "No último minuto, põe o queijo (e o fiambre, se usares) sobre o pão e deixa amolecer com o calor da frigideira tapada ou no microondas 20–30 segundos.",
        "Empilha o ovo em cima da tosta com queijo e serve quente.",
      ],
    },
    {
      section: "manha",
      title: "Wrap de peito de peru e ovo",
      subtitle: "Para levar · 10 min",
      protein_note: "~28 g proteína",
      tags: ["leva-te"],
      ingredients: [
        "1 tortilha grande de trigo",
        "2–3 fatias de peito de peru",
        "1 ovo",
        "1 colher de sopa de cream cheese ou queijo creme",
        "Manteiga ou azeite",
        "Sal e pimenta",
      ],
      steps: [
        "Frita ou mexe o ovo numa frigideira com um pouco de manteiga. Tempera com sal e pimenta. Reserva.",
        "Aquece a tortilha 15–20 segundos na frigideira seca ou 10 segundos no microondas, só para ficar flexível.",
        "Espalha o cream cheese no centro da tortilha, deixando as bordas livres.",
        "Distribui o peito de peru e o ovo por cima.",
        "Dobra os lados e enrola com firmeza. Corta ao meio se for para a estrada.",
      ],
    },

    // —— Praia / frio ——
    {
      section: "praia",
      title: "Patê de atum clássico",
      subtitle: "Sandes ou wrap · fria",
      protein_note: "atum = proteína",
      tags: ["mala térmica", "clássico"],
      ingredients: [
        "1 lata grande de atum em água ou azeite (escoada)",
        "2–3 colheres de sopa de maionese",
        "1 ovo cozido (opcional, mas clássico)",
        "Sal, pimenta e orégãos a gosto",
        "Opcional: 1 colher de chá de mostarda Dijon",
        "Pão de forma mole, baguete ou wrap",
        "Alface (leva à parte para não amolecer o pão)",
      ],
      steps: [
        "Se usares ovo: coze 9–10 minutos em água a ferver, passa por água fria, descasca e pica miúdo.",
        "Escorre bem o atum e desfaz com um garfo numa taça até ficar em flocos finos.",
        "Junta a maionese (e a mostarda, se usares). Mistura até obter um patê cremoso e homogéneo.",
        "Incorpora o ovo picado. Tempera com sal, pimenta e orégãos. Prova e ajusta.",
        "Espalha no pão ou wrap. A alface só na hora de comer, se possível.",
        "Mantém sempre na mala térmica com gelo — maionese e atum não gostam de calor.",
      ],
      note: "Conserva refrigerado. Em dias de praia, come nas primeiras horas e não deixes ao sol.",
    },
    {
      section: "praia",
      title: "Wrap de frango desfiado",
      subtitle: "Preparar à noite",
      protein_note: "~30 g proteína",
      tags: ["preparar à noite"],
      ingredients: [
        "250–300 g de frango cozido ou assado desfiado",
        "2–3 colheres de sopa de maionese (ou metade maionese + metade iogurte grego)",
        "Sumo de ½ limão",
        "Sal, pimenta e orégãos",
        "2 tortilhas grandes",
        "Folhas de alface",
      ],
      steps: [
        "Desfia o frango com dois garfos até ficar em fios finos (frango assado do supermercado serve bem).",
        "Numa taça, mistura o frango com a maionese, o limão, sal, pimenta e orégãos até ficar cremoso e bem envolvido.",
        "Prova e ajusta o tempero — deve ficar saboroso a frio.",
        "Aquece ligeiramente as tortilhas para enrolarem sem rachar.",
        "Espalha o recheio, põe alface, enrola apertado e embrulha em película ou papel.",
        "Guarda no frio até sair de casa.",
      ],
    },
    {
      section: "praia",
      title: "Sandes de ovo e maionese",
      subtitle: "Clássica britânica · fria",
      protein_note: "~20 g proteína",
      tags: ["fria", "clássico"],
      ingredients: [
        "4 ovos",
        "2–3 colheres de sopa de maionese",
        "Sal e pimenta",
        "Opcional: ½ colher de chá de mostarda",
        "8 fatias de pão de forma mole",
        "Manteiga (opcional, nas fatias)",
      ],
      steps: [
        "Coze os ovos 9–10 minutos. Escorre e passa por água fria para parar a cozedura.",
        "Descasca e esmaga com um garfo — deixa alguns pedaços, não transformes em papa.",
        "Mistura a maionese (e a mostarda). Tempera com sal e pimenta até ficar cremoso.",
        "Se quiseres pão menos húmido, unta as fatias com uma película fina de manteiga antes do recheio.",
        "Espalha o recheio, tapa com a outra fatia e corta ao meio em triângulo.",
        "Embrulha e mantém fresco até à praia.",
      ],
    },
    {
      section: "praia",
      title: "Bagel de salmão fumado e cream cheese",
      subtitle: "Sem fogão · 5 min",
      protein_note: "~25 g proteína",
      tags: ["sem fogão"],
      ingredients: [
        "100–120 g de salmão fumado",
        "3–4 colheres de sopa de cream cheese",
        "2 wraps ou 1 baguete macia",
        "Sumo de limão",
        "Pimenta preta",
        "Opcional: endro ou cebolinho picado",
      ],
      steps: [
        "Espalha o cream cheese em camada fina e uniforme no wrap ou na baguete aberta.",
        "Distribui as fatias de salmão sem sobrepor demasiado.",
        "Rega com umas gotas de limão, pimenta e as ervas, se usares.",
        "Enrolha com firmeza (no wrap) ou fecha a baguete. Corta em porções.",
        "Mantém bem frio até servir.",
      ],
    },

    // —— Lanches ——
    {
      section: "lanches",
      title: "Ovos cozidos com sal",
      subtitle: "Batch · cabem no saco",
      protein_note: "~6 g / ovo",
      tags: ["soft", "meal prep"],
      ingredients: ["Ovos (quantos quiseres)", "Sal grosso ou fino", "Água"],
      steps: [
        "Coloca os ovos numa panela numa só camada e cobre com água fria (2 cm acima).",
        "Leva a lume médio-alto. Quando ferver, conta 9 minutos para gema cremosa ou 11 para gema firme.",
        "Escorre e passa logo por água fria (ou taça com gelo) durante 2–3 minutos.",
        "Descasca com cuidado ou leva com casca e descasca na hora.",
        "Come com uma pitada de sal. Guardam 3–4 dias no frigorífico.",
      ],
    },
    {
      section: "lanches",
      title: "Smoothie de banana, leite e amendoim",
      subtitle: "Bebível · 3 min",
      protein_note: "~18–25 g",
      tags: ["líquido"],
      ingredients: [
        "1 banana madura",
        "300 ml de leite (ou bebida vegetal)",
        "1–2 colheres de sopa de pasta de amendoim cremosa",
        "Opcional: 2–3 colheres de sopa de iogurte grego",
        "Opcional: 1 colher de chá de mel",
      ],
      steps: [
        "Corta a banana em pedaços e mete no liquidificador ou varinha.",
        "Junta o leite, a pasta de amendoim e o iogurte/mel se usares.",
        "Tritura 30–60 segundos até ficar completamente liso, sem grumos de amendoim.",
        "Prova: se estiver pouco doce, mais um pouco de mel ou banana mais madura.",
        "Serve fresco. Em garrafa térmica, leva gelo se for para a praia.",
      ],
    },
    {
      section: "lanches",
      title: "Queijo fresco no pão de leite",
      subtitle: "Espalha e come",
      protein_note: "~12–18 g",
      tags: ["soft"],
      ingredients: [
        "Queijo fresco, requeijão ou ricotta",
        "Pão de leite ou brioche",
        "Opcional: 1–2 fatias finas de fiambre",
        "Opcional: orégãos e um fio de azeite",
      ],
      steps: [
        "Abre o pão ao meio.",
        "Espalha uma camada generosa de queijo fresco.",
        "Se quiseres, põe fiambre por cima e um pouco de orégãos.",
        "Fecha e come — ou tosta 1 minuto na frigideira se preferires morno.",
      ],
    },

    // —— Jantar ——
    {
      section: "jantar",
      title: "Hambúrgueres caseiros",
      subtitle: "Carne · queijo · pão",
      protein_note: "~35–45 g",
      tags: ["estrela", "clássico"],
      ingredients: [
        "400 g de carne picada (vaca ou misturada)",
        "Sal e pimenta",
        "2 pães de hambúrguer",
        "2 fatias de queijo cheddar ou flamengo",
        "Alface, tomate e cebola",
        "Molhos a gosto (maionese, ketchup, mostarda)",
        "Azeite ou manteiga para a frigideira",
      ],
      steps: [
        "Divide a carne em 2 porções iguais. Forma discos um pouco mais largos que o pão (encolhem ao cozer). Não amasses em excesso.",
        "Tempra só com sal e pimenta dos dois lados, na hora de ir à frigideira.",
        "Aquece bem a frigideira ou grelhador com um fio de azeite em lume médio-alto.",
        "Coze 3–4 minutos do primeiro lado sem mexer. Vira e coze mais 3–4 minutos (ao ponto) ou até ao ponto que gostas.",
        "No último minuto, põe o queijo em cima, tapa a frigideira 30–60 segundos para derreter.",
        "Tosta ligeiramente os pães na frigideira. Monta: base → molho → carne → vegetais → topo.",
      ],
    },
    {
      section: "jantar",
      title: "Esparguete à bolonhesa rápida",
      subtitle: "Carne picada · 30 min",
      protein_note: "~30–40 g",
      tags: ["clássico", "1 panela"],
      ingredients: [
        "300–400 g de esparguete ou outra massa longa",
        "400 g de carne picada",
        "1 cebola média picada",
        "2 dentes de alho picados",
        "400 g de tomate pelado ou passata",
        "Azeite, sal, pimenta e orégãos",
        "Queijo ralado para servir",
      ],
      steps: [
        "Põe água generosa a ferver com sal. Coze a massa no tempo da embalagem; reserva 1 concha da água da cozedura antes de escorrer.",
        "Enquanto isso, aquece azeite num tacho em lume médio. Refoga a cebola 4–5 minutos até amolecer. Junta o alho 30 segundos.",
        "Aumenta o lume, deita a carne e desfaz com a colher de pau. Coze até perder a cor rosada e começar a dourar.",
        "Junta o tomate, sal, pimenta e orégãos. Baixa o lume e deixa apurar 12–15 minutos, mexendo de vez em quando.",
        "Se o molho estiver muito espesso, afrouxa com um pouco da água da massa.",
        "Mistura a massa escorrida com o molho no tacho. Serve com queijo ralado por cima.",
      ],
    },
    {
      section: "jantar",
      title: "Bifanas no pão",
      subtitle: "À portuguesa",
      protein_note: "~35–40 g",
      tags: ["tacho", "clássico"],
      ingredients: [
        "350–400 g de bifanas (porco em fatias finas)",
        "3–4 dentes de alho esmagados",
        "1 folha de louro",
        "1 dl de vinho branco seco (ou cerveja)",
        "Azeite ou banha, sal, pimenta e colorau doce a gosto",
        "Pão de trigo bom (papo-seco ou similar)",
        "Opcional: mostarda",
      ],
      steps: [
        "Tempra as bifanas com sal, pimenta e um pouco de colorau.",
        "Num tacho ou frigideira funda, aquece azeite em lume médio-alto. Doura o alho e o louro sem queimar.",
        "Deita as bifanas e deixa selar 1–2 minutos de cada lado.",
        "Rega com o vinho branco. Quando ferver, baixa o lume e deixa reduzir 8–12 minutos até o molho engrossar e a carne ficar tenra.",
        "Prova o molho e ajusta o sal.",
        "Abre o pão, molha o miolo no molho da panela, mete as bifanas e um pouco mais de molho. Mostarda a gosto.",
      ],
    },
    {
      section: "jantar",
      title: "Frango panado na frigideira",
      subtitle: "Com batata · 25 min",
      protein_note: "~40 g",
      tags: ["frigideira"],
      ingredients: [
        "2 peitos de frango cortados em filetes finos",
        "1 ovo batido",
        "Pão ralado temperado com sal, pimenta e orégãos",
        "Azeite ou óleo para fritar",
        "Batatas para acompanhar (cozidas, salteadas ou fritas)",
        "Limão e maionese a gosto",
      ],
      steps: [
        "Seca bem os filetes com papel de cozinha. Tempera levemente com sal.",
        "Passa cada filete no ovo batido e depois no pão ralado, pressionando para aderir bem dos dois lados.",
        "Aquece uma camada generosa de azeite/óleo numa frigideira em lume médio.",
        "Frita os filetes 3–4 minutos de cada lado até o panado estar dourado e o frango cozido no centro (não deve ficar rosado).",
        "Escorre em papel de cozinha.",
        "Serve com batata, um quarto de limão e maionese.",
      ],
    },
    {
      section: "jantar",
      title: "Esparguete de atum e alho",
      subtitle: "Despensa · 15 min",
      protein_note: "~30 g",
      tags: ["lata", "rápido"],
      ingredients: [
        "250 g de esparguete",
        "2 latas de atum escorridas",
        "3 dentes de alho laminados",
        "4 colheres de sopa de azeite",
        "Malagueta seca ou flocos (opcional)",
        "Orégãos, sal e pimenta",
        "Opcional: queijo ralado",
      ],
      steps: [
        "Coze o esparguete em água bem salgada. Antes de escorrer, guarda 1 concha da água da cozedura.",
        "Numa frigideira larga, aquece o azeite em lume médio-baixo. Junta o alho (e a malagueta) e deixa perfumar 1–2 minutos sem dourar demasiado.",
        "Adiciona o atum e desfaz ligeiramente. Envolve no azeite 1 minuto.",
        "Deita a massa escorrida na frigideira. Junta um pouco da água da cozedura e mistura com força para criar um molho ligeiro.",
        "Tempra com orégãos, pimenta e sal se precisar. Serve de imediato.",
      ],
    },
    {
      section: "jantar",
      title: "Omelete de fiambre e queijo",
      subtitle: "Jantar rápido · 10 min",
      protein_note: "~30–35 g",
      tags: ["preguiçoso", "ovos"],
      ingredients: [
        "4 ovos",
        "2–3 fatias de fiambre picado",
        "Queijo ralado generoso (2–3 colheres de sopa)",
        "Manteiga ou azeite",
        "Sal e pimenta",
        "Pão ou salada para acompanhar",
      ],
      steps: [
        "Bate os ovos numa taça com sal e pimenta até homogeneizar.",
        "Aquece a manteiga numa frigideira antiaderente em lume médio.",
        "Deita os ovos. Deixa começar a coagular nas bordas; com a espátula, puxa as bordas para o centro e inclina a frigideira para o líquido ocupar o espaço.",
        "Quando a superfície estiver quase presa mas ainda húmida, espalha o fiambre e o queijo numa metade.",
        "Dobra a omelete ao meio com a espátula e deixa o queijo derreter 30–60 segundos.",
        "Escorre para o prato e serve.",
      ],
    },
  ],

  shoppingLists: [
    {
      name: "Supermercado",
      items: [
        "Ovos",
        "Atum em lata",
        "Peito de frango ou frango assado",
        "Carne picada",
        "Bifanas",
        "Fiambre / peito de peru",
        "Salmão fumado",
        "Iogurte grego",
        "Queijo (fatias + ralado)",
        "Cream cheese / queijo fresco",
        "Pasta de amendoim",
        "Pão mole / de forma / de leite",
        "Wraps / tortilhas",
        "Pão de hambúrguer",
        "Massa (esparguete)",
        "Maionese",
        "Tomate pelado / passata",
        "Leite",
        "Mel e granola",
        "Pão ralado",
        "Alface, tomate, cebola",
        "Alho",
        "Bananas",
        "Limões",
        "Batatas",
        "Azeite e manteiga",
        "Sal, pimenta, orégãos",
      ],
    },
    {
      name: "Praia / mala térmica",
      items: [
        "Gelo / acumuladores de frio",
        "Mala térmica",
        "Água e sumos",
        "Wraps ou pão mole",
        "Patê / sandes já feitas",
        "Ovos cozidos",
        "Fruta mole (banana, pêssego)",
        "Guardanapos e sacos",
      ],
    },
  ],
};
